---
title: "alpha_diversity"
output: html_document
date: "2024-10-10"
---

#load packages

```{r}
library(readxl)
library(phyloseq)
library(tidyverse)
library(vegan)
library(picante)
library(glm2)
library(lawstat)
library(gridExtra)
library(gtable)
```

#path to raw-data directory (change "path" to your raw-data directory)

```{r}
#create "path" file, and define "path" as your raw-data directory(character vector) in the file
#"path" is raw-data directory, and "path_out" is output file directory

source("../scripts/path.R")
```

#source codes

```{r}
source("../R/occurrence.R")
source("../R/label.R")
```

#read processed data

```{r import}
df_rarefied <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/df_rarefied_ITS.csv"), row.names = 1)
rownames(df_rarefied) <- formatC(as.numeric(rownames(df_rarefied)), width = 4, flag = "0") 
#add 0 to the head of rownames

otu_ITS <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/otus_data_ITS.csv"), row.names = 1)
rownames(otu_ITS) <- formatC(as.numeric(rownames(otu_ITS)), width = 4, flag = "0") 

tax_table <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/tax_table2_ITS.csv"), row.names = 1)
tax_table <- as.matrix(tax_table)

load(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/trees.Rdata"))

metadata <- read_excel(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/metadata_2306.xlsx"), 
                       sheet = "Sheet1")
metadata <- column_to_rownames(metadata, var = "Sample_Name")
metadata$cloneID <- as.factor(metadata$cloneID)
metadata$population <- as.factor(metadata$population)
metadata$site <- as.factor(metadata$site)
metadata$date <- as.factor(metadata$date)

location <- read_excel(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/location_Sugi_pop.xlsx"), sheet = "location")

#merge sample-metadata and population metadata
metadata_loc <- left_join(metadata, location, by = "population")
rownames(metadata_loc) <- formatC(as.numeric(rownames(metadata_loc)), width = 4, flag = "0")
```

#phyloseq

```{r}
ps_ITS_rf <- phyloseq(otu_table(t(df_rarefied), taxa_are_rows = TRUE), 
                   tax_table(tax_table), 
                   sample_data(metadata_loc), 
                   phy_tree(tree_rarefied2$data))

ps_ITS <- phyloseq(otu_table(t(otu_ITS), taxa_are_rows = TRUE), 
                   tax_table(tax_table), 
                   sample_data(metadata_loc), 
                   phy_tree(tree_rarefied2$data))

sum(apply(df_rarefied > 0, 2, sum) > 0)
sum(apply(otu_ITS > 0, 2, sum) > 0)
```

#phylogenetic distance

```{r}
phydist <- cophenetic(tree_rarefied2$data)
```

#alpha-diversity-indices

```{r}
#package "vegan"
metadata_loc$richness <- specnumber(df_rarefied)
metadata_loc$shannon <- diversity(df_rarefied, index = "shannon")
metadata_loc$simpson <- diversity(df_rarefied, index = "simpson")
faith <- pd(df_rarefied, tree_rarefied2$data, include.root = TRUE)
#faith's phylogenetic diversity(package "picante")
metadata_loc <- cbind(metadata_loc, faith)
metadata_loc$wmpd <- mpd(df_rarefied, phydist, abundance.weighted = TRUE)
```

##richness

```{r}
p_rich <- ggplot(data = metadata_loc, 
                 mapping = aes(x = latitude, y = richness)) + 
  geom_point(mapping = aes(color = site), size = 2) +
  theme_classic() + 
  xlim(c(30, 41)) + #ylim(0, 300) +
  scale_color_manual(values = c("blue3", "orange3")) +
  labs(x = "Latitude", y = "Richness", color = "Site") +
  theme(text = element_text(size = 10), 
        legend.position = "inside", 
        legend.title = element_text(size = 13), 
        legend.text = element_text(size = 10))

p_shannon <- ggplot(data = metadata_loc, 
                    mapping = aes(x = latitude, y = shannon)) + 
  geom_point(mapping = aes(color = site), size = 2) +
  theme_classic() + 
  xlim(c(30, 41)) + #ylim(0, 300) +
  scale_color_manual(values = c("blue3", "orange3")) +
  labs(x = "Latitude", 
       y = expression(paste("Shannon's ",  italic("H'"))), 
       color = "Site") +
  theme(text = element_text(size = 10))

p_simp <- ggplot(data = metadata_loc, 
                 mapping = aes(x = latitude, y = simpson)) + 
  geom_point(mapping = aes(color = site), size = 2) +
  theme_classic() + 
  xlim(c(30, 41)) + #ylim(0, 300) +
  scale_color_manual(values = c("blue3", "orange3")) +
  labs(x = "Latitude", 
       y = expression(paste("Simpson's ",  italic("D"))), 
       color = "Site") +
  theme(text = element_text(size = 10))

p_faith <- ggplot(data = metadata_loc, 
                  mapping = aes(x = latitude, y = PD)) + 
  geom_point(mapping = aes(color = site), size = 2) +
  theme_classic() + 
  xlim(c(30, 41)) + #ylim(0, 300) +
  scale_color_manual(values = c("blue3", "orange3")) +
  labs(x = "Latitude", y = "Faith's PD", color = "Site") +
  theme(text = element_text(size = 10))

p_wmpd <- ggplot(data = metadata_loc, 
                 mapping = aes(x = latitude, y = wmpd)) + 
  geom_point(mapping = aes(color = site), size = 2) +
  theme_classic() + 
  xlim(c(30, 41)) + #ylim(0, 300) +
  scale_color_manual(values = c("blue3", "orange3")) +
  labs(x = "Latitude", 
       y = "WMPD", 
       color = "Site") +
  theme(text = element_text(size = 10))

legend <- gtable_filter(ggplotGrob(p_rich), "guide-box")
```

```{r}
pl_rich <- p_rich + theme(legend.position = "none")
pl_shannon <- p_shannon + theme(legend.position = "none")
pl_simp <- p_simp + theme(legend.position = "none")
pl_faith <- p_faith + theme(legend.position = "none")
pl_wmpd <- p_wmpd + theme(legend.position = "none")

pl_rich <- arrangeGrob(pl_rich, top = create_label("a"))
pl_shannon <- arrangeGrob(pl_shannon, top = create_label("b"))
pl_simp <- arrangeGrob(pl_simp, top = create_label("c"))
pl_faith <- arrangeGrob(pl_faith, top = create_label("d"))
pl_wmpd <- arrangeGrob(pl_wmpd, top = create_label("e"))

p_div <- grid.arrange(pl_rich, pl_shannon, pl_simp, pl_faith, pl_wmpd, legend, 
                      nrow = 2, ncol = 3)

ggsave(p_div, filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/figures/alpha_ITS.png"), 
       dpi = 400, width = 150, height = 100, units = "mm")
```

#glm

```{r}
lm_rich <- glm2(richness ~ site * latitude, 
                data = metadata_loc, 
                family = Gamma(link = "inverse"))
summary(lm_rich)

write.csv(cbind(summary(lm_rich)$coefficients, 
                AIC = summary(lm_rich)$aic), 
          file = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/analysis/rich_glm_gamma.csv"))
```

```{r}
levene_shan <- levene.test(metadata_loc$shannon, metadata_loc$site)

write.csv(cbind(W = levene_shan$statistic, p = levene_shan$p.value), 
          file = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/analysis/shannon_levene.csv"))

lm_shan <- glm2(shannon ~ site * latitude, 
                data = metadata_loc, 
                family = gaussian)
summary(lm_shan)

write.csv(cbind(summary(lm_shan)$coefficients, 
                AIC = summary(lm_shan)$aic), 
          file = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/analysis/shannon_glm_gauss.csv"))
```

```{r}
lm_simp <- glm2(simpson ~ site * latitude, 
                data = metadata_loc, 
                family = Gamma(link = "inverse"))
summary(lm_simp)

write.csv(cbind(summary(lm_simp)$coefficients, 
                AIC = summary(lm_simp)$aic), 
          file = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/analysis/simpson_glm_gamma.csv"))
```

```{r}
levene_faith <- levene.test(metadata_loc$PD, group = metadata_loc$site)

write.csv(cbind(W = levene_faith$statistic, p = levene_faith$p.value), 
          file = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/analysis/faith_levene.csv"))

lm_faith <- glm2(PD ~ site * latitude, 
                data = metadata_loc, 
                family = Gamma(link = "inverse"))
summary(lm_faith)

write.csv(cbind(summary(lm_faith)$coefficients, 
                AIC = summary(lm_faith)$aic), 
          file = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/analysis/faith_glm_gamma.csv"))
```

```{r}
#Weighted Mean Phylogenetic Distance
#There is large difference between the variances of wmpd in Kawatabi and Tsukuba (Levene's test)
levene_wmpd <- levene.test(metadata_loc$wmpd, metadata_loc$site)

write.csv(cbind(W = levene_wmpd$statistic, p = levene_wmpd$p.value), 
          file = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/analysis/wmpd_levene.csv"))

lm_wmpd <- glm2(wmpd ~ site * latitude, 
                data = metadata_loc, 
                family = gaussian)
summary(lm_wmpd)


write.csv(cbind(summary(lm_wmpd)$coefficients, 
                AIC = summary(lm_wmpd)$aic), 
          file = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/analysis/wmpd_glm_gauss.csv"))
```

