---
title: "barplot"
output: html_document
date: "2024-10-10"
---

#load packages

```{r}
library(readxl)
library(phyloseq)
library(fantaxtic)
library(tidyverse)
library(ggnested)
library(ggtext)
library(gridExtra)
library(grid)
library(gtable)
```

#path to raw-data directory (change "path" to your raw-data directory)

```{r}
#create "path" file, and define "path" as your raw-data directory(character vector) in the file
#"path" is raw-data directory, and "path_out" is output file directory

source("../scripts/path.R")
```

#source codes
```{r}
source("../R/label.R")
source("../R/top_nest.R")
```

#read processed data
##16S

```{r import}
otus_16S <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/processed_data/otus_data_16S.csv"), row.names = 1)
rownames(otus_16S) <- formatC(as.numeric(rownames(otus_16S)), width = 4, flag = "0") #add 0 to rownames

#tax_table
tax_16S <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/processed_data/tax_table2_16S.csv"), row.names = 1)
tax_16S <- as.matrix(tax_16S)

#phylogenetic tree
load(paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/processed_data/trees.Rdata"))
tree16S <- tree2
tree16S_rarefied <- tree_rarefied2
rm(list = c("tree2", "tree_rarefied2"))

#metadata
metadata <- read_excel(paste0(path_out, "/data/Sugi/metadata_2306.xlsx"), sheet = "Sheet1")
metadata <- column_to_rownames(metadata, var = "Sample_Name")
metadata$cloneID <- as.factor(metadata$cloneID)
metadata$population <- as.factor(metadata$population)
metadata$site <- as.factor(metadata$site)
metadata$date <- as.factor(metadata$date)
```

##ITS

```{r}
otus_ITS <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/otus_data_ITS.csv"), row.names = 1)
rownames(otus_ITS) <- formatC(as.numeric(rownames(otus_ITS)), width = 4, flag = "0") #add 0 to rownames

#tax_table
tax_ITS <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/tax_table2_ITS.csv"), row.names = 1)
tax_ITS <- as.matrix(tax_ITS)

#phylogenetic tree
load(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/trees.Rdata"))
treeITS <- tree2
treeITS_rarefied <- tree_rarefied2
rm(list = c("tree2", "tree_rarefied2"))
```


```{r}
# add clone_ID to rownames (why needed?)
rownames(otus_16S) <- paste0(rownames(metadata), "_", metadata$population)
rownames(otus_ITS) <- paste0(rownames(metadata), "_", metadata$population)
rownames(metadata) <- paste0(rownames(metadata), "_", metadata$population)
```

#arrange data

```{r}
#sort metadata in decreacing order accordance with latitude
meta_lat <- metadata %>%
  arrange(latitude) %>%
  arrange(site)

otus_16S_lat <- otus_16S[rownames(meta_lat), ]
otus_ITS_lat <- otus_ITS[rownames(meta_lat), ]

#make xlabel vector (population name of samples at center position within samples with the same population)
site_pop <- as.factor(paste0(meta_lat$site, "_", meta_lat$population))
sitepop_row <- sapply(levels(site_pop), grep, site_pop)
vline <- sapply(sitepop_row, min)
sitepop_row <- sapply(sitepop_row, median)
sitepop_row <- sapply(sitepop_row, floor)

meta_lat$xlab <- rep("", nrow(meta_lat))
meta_lat$xlab[sitepop_row] <- as.character(meta_lat$population[sitepop_row])

vline = data.frame("line" = vline - 0.5)
```

#phyloseq_object

```{r barplot}
ps_16S <- phyloseq(otu_table(otus_16S_lat, taxa_are_rows = F), 
                 tax_table(tax_16S), 
                 phy_tree(tree16S$data), 
                 sample_data(meta_lat)) #change row indices to choose samples included in barplots
ps_ITS <- phyloseq(otu_table(otus_ITS_lat, taxa_are_rows = F), 
                 tax_table(tax_ITS), 
                 phy_tree(treeITS$data), 
                 sample_data(meta_lat))
```

#plot
##16S

```{r, cache=TRUE, dependson="barplot"}
#make plot by yourself!!
#select highly abundant taxa
top_16S <- top_nest(ps_obj = ps_16S, 
                    tax_level = "Genus", 
                    top_level = "Phylum", 
                    n = 5, 
                    grouping = "site")
```

###kawatabi

```{r}
top_16S_k <- subset_samples(top_16S$ps_obj, site == "Kawatabi")

p_16S_k <- plot_nested_bar(ps_obj = top_16S_k, 
                           top_level = "Phylum", 
                           nested_level = "Genus") +
  theme_classic() +
  scale_x_discrete(labels = meta_lat[meta_lat$site == "Kawatabi", "xlab"]) +
  geom_vline(xintercept = vline[1:14, "line"], 
             linetype = "dashed", color = "black") +
  labs(x = "Kawatabi", y = "Relative Abundance") +
  theme(axis.title.x = element_text(), 
        axis.text.x = element_text(),
        axis.ticks.x = element_blank(),
        
        legend.text = element_markdown(size = 10), 
        legend.key.size = unit(7, "mm"), 
        legend.spacing.x = unit(5, "mm"), 
        legend.position = "inside")
```

###tsukuba

```{r}
top_16S_t <- subset_samples(top_16S$ps_obj, site == "Tsukuba")

p_16S_t <- plot_nested_bar(ps_obj = top_16S_t, 
                         top_level = "Phylum", 
                         nested_level = "Genus") +
  theme_classic() +
  scale_x_discrete(labels = meta_lat[meta_lat$site == "Tsukuba", "xlab"]) +
  geom_vline(xintercept = vline[15:28, "line"]-58, 
             linetype = "dashed", color = "black") +
  labs(x = "Tsukuba", y = "Relative Abundance") +
  theme(axis.title.x = element_text(), 
        axis.text.x = element_text(),
        axis.ticks.x = element_blank(),
        
        legend.text = element_markdown(), 
        legend.key.size = unit(7, "mm"), 
        legend.position = "inside")
```

##ITS

```{r}
top_ITS <- top_nest(ps_obj = ps_ITS, 
                    tax_level = "Family", 
                    top_level =  "Class", 
                    n = 6, 
                    grouping = "site"
                    )
```

###kawatabi

```{r}
top_ITS_k <- subset_samples(top_ITS$ps_obj, site == "Kawatabi")

p_ITS_k <- plot_nested_bar(ps_obj = top_ITS_k, 
                      top_level = "Class", 
                      nested_level = "Family") +
  theme_classic() +
  scale_x_discrete(labels = meta_lat[meta_lat$site == "Kawatabi", "xlab"]) +
  geom_vline(xintercept = vline[1:14, "line"], 
             linetype = "dashed", color = "black") +
  labs(x = "Kawatabi", y = "Relative Abundance") +
  theme(axis.title.x = element_text(), 
        axis.text.x = element_text(),
        axis.ticks.x = element_blank(),
        
        legend.text = element_markdown(size = 10), 
        legend.key.size = unit(7, "mm"), 
        legend.spacing.x = unit(5, "mm"), 
        legend.position = "inside")
```

###tsukuba

```{r}
top_ITS_t <- subset_samples(top_ITS$ps_obj, site == "Tsukuba")

p_ITS_t <- plot_nested_bar(ps_obj = top_ITS_t, 
                      top_level = "Class", 
                      nested_level = "Family") +
  theme_classic() +
  scale_x_discrete(labels = meta_lat[meta_lat$site == "Tsukuba", "xlab"]) +
  geom_vline(xintercept = vline[15:28, "line"]-58, 
             linetype = "dashed", color = "black") +
  labs(x = "Tsukuba", y = "Relative Abundance") +
  theme(axis.title.x = element_text(), 
        axis.text.x = element_text(),
        axis.ticks.x = element_blank(),
        
        legend.text = element_markdown(), 
        legend.key.size = unit(7, "mm"), 
        legend.position = "inside")
```

#arrange tow plots

```{r}
legend_16S <- gtable_filter(ggplotGrob(p_16S_k), "guide-box")
legend_ITS <- gtable_filter(ggplotGrob(p_ITS_k), "guide-box")

pl_16S_k <- p_16S_k + theme(legend.position = "none")
pl_16S_t <- p_16S_t + theme(legend.position = "none")
pl_ITS_k <- p_ITS_k + theme(legend.position = "none")
pl_ITS_t <- p_ITS_t + theme(legend.position = "none")

pl_16S_k <- arrangeGrob(pl_16S_k, top = create_label("a"))
pl_16S_t <- arrangeGrob(pl_16S_t, top = create_label("b"))
pl_ITS_k <- arrangeGrob(pl_ITS_k, top = create_label("c"))
pl_ITS_t <- arrangeGrob(pl_ITS_t, top = create_label("d"))

p_16S <- grid.arrange(pl_16S_k, pl_16S_t, nrow = 1)
p_ITS <- grid.arrange(pl_ITS_k, pl_ITS_t, nrow = 1)

p_all <- grid.arrange(pl_16S_k, pl_16S_t, legend_16S, pl_ITS_k, pl_ITS_t, legend_ITS,
                      ncol = 3, nrow = 2, widths = c(1, 1, 0.5))

ggsave(plot = p_16S, filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/figures/barplot_16S.png"), 
       dpi = 400, width = 150, height = 80, units = "mm", scale = 2)
ggsave(plot = p_ITS, filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/figures/barplot_ITS.png"), 
       dpi = 400, width = 150, height = 80, units = "mm", scale = 2)
ggsave(p_all, filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/figures/barplot_both.png"), 
       dpi = 400, width = 150, height = 160, units = "mm", scale = 2.5)
```

```{r}
legend <- grid.arrange(legend_16S, legend_ITS, nrow = 1, ncol = 2)
ggsave(legend_16S, filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/figures/barplot_legend.png"), 
       dpi = 400, width = 120, height = 80, units = "mm")
ggsave(legend_ITS, filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/figures/barplot_legend.png"), 
       dpi = 400, width = 120, height = 80, units = "mm")
ggsave(legend, filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/figures/barplot_legend_both.png"), 
       dpi = 400, width = 150, height = 160, units = "mm")
```

