---
title: "BVOC_table"
output: html_document
date: "2025-01-23"
---

#load packages

```{r}
library(readxl)
library(tidyverse)
library(gridExtra)
library(grid)
library(gtable)
library(gt)
```

#path to raw-data directory (change "path" to your raw-data directory)

```{r}
#create "path" file, and define "path" as your raw-data directory(character vector) in the file
#"path" is raw-data directory, and "path_out" is output file directory

source("../scripts/path.R")
```

#source codes

```{r}
#source("../R/bestNMDS.R")
source("../R/html_italic.R")
source("../R/Greek.R")
source("../R/md_italic.R")
source("../R/gg_italic.R")
```

#read processed data

```{r import}
#rarefied_ASV_table
metadata <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/processed_data/BVOC/metadata_16S_BVOC.csv"), row.names = 1)
rownames(metadata) <- formatC(as.numeric(rownames(metadata)), width = 4, flag = "0")

metadata$cloneID <- as.factor(metadata$cloneID)
metadata$population <- as.factor(metadata$population)
metadata$site <- as.factor(metadata$site)
metadata$date <- as.factor(metadata$date)

#population metadata
meta_pop <- read_excel(paste0(path_out, "/data/Sugi/metadata_2306.xlsx"), sheet = "location")

#result of PCA on climatic variables
load(paste0(path_out, "/data/Sugi/pca_climate.Rdata"))
df_pcaclim <- data.frame(pca_clim$x)
colnames(df_pcaclim) <- paste0(colnames(df_pcaclim), "_clim")

#merge population metadata and PCA result
meta_pop <- cbind(meta_pop, df_pcaclim)

#basal emission rates of BVOCs
BVOC_2306 <- read_excel(paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/processed_data/BVOC/BVOC_summary_240122.xlsx"), 
                       sheet = "2306_KAWATABI")
BVOC_2306 <- column_to_rownames(BVOC_2306, var = "samplename")
rawcol <- colnames(BVOC_2306)
nonitalic <- greek(colnames(BVOC_2306))
colnames(BVOC_2306) <- html_italic(colnames(BVOC_2306), sep = "-")
colnames(BVOC_2306) <- greek(colnames(BVOC_2306))

#log-transformed BVOC emission data
load(paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/processed_data/BVOC/BVOC_2306_16S_log.Rdata"))
colnames(BVOC_2306_log) <- greek(colnames(BVOC_2306_log))
```

#output basal emission table

```{r}
BVOC_tbl <- BVOC_2306
colnames(BVOC_tbl) <- rawcol
BVOC_tbl <- rownames_to_column(BVOC_tbl, var = "Samplename")

BVOC_tbl <- BVOC_tbl %>% 
  gt::gt() %>%
  gt::tab_style(cell_text(weight = "bold"), locations = cells_column_labels(columns = everything())) %>%
  gt::cols_label(`alpha-Pinene` = md("*α*-Pinene"), 
                 `beta-Pinene` = md("*β*-Pinene"), 
                 `alpha-Terpinene` = md("*α*-Terpinene"), 
                 `beta-Farnesene` = md("*β*-Farnesene"), 
                 `gamma-Terpinene` = md("*γ*-Terpinene"), 
                 `p-Cymene` = md("*p*-Cymene"), 
                 `Methyl salicylate` <- md("Methyl/nSalicylate"), 
                 `ent-Kaurene` = md("*ent*-Kaurene")) %>%
  cols_width(everything() ~ px(1800 / (ncol(BVOC_2306)+1))) %>%
  tab_options(table.font.names = "Times New Roman")

show(BVOC_tbl)

gtsave(BVOC_tbl, file = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/export/BVOC_BE.png"), 
       vwidth = 1890, vheight = 1417)
gtsave(BVOC_tbl, file = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/export/BVOC_BE.pdf"), 
       vwidth = 1890, vheight = 1417)


```

