---
title: "envfit_BVOC_ITS"
output: html_document
date: "2024-10-10"
---

#load packages

```{r}
library(readxl)
library(phyloseq)
library(tidyverse)
library(vegan)
library(RColorBrewer)
library(SummarizedExperiment)
```

#path to raw-data directory (change "path" to your raw-data directory)

```{r}
#create "path" file, and define "path" as your raw-data directory(character vector) in the file
#"path" is raw-data directory, and "path_out" is output file directory

source("../scripts/path.R")
```

#source codes

```{r}
source("../R/bestNMDS.R")
```

#read processed data

```{r import}
#the microbiome outlier (AZ_040_1, based on bray) is excluded in advance
#rarefied-ASV table
df_rarefied <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/df_rarefied_ITS.csv"), row.names = 1)
rownames(df_rarefied) <- formatC(as.numeric(rownames(df_rarefied)), width = 4, flag = "0") 
#add 0 to the head of rownames

#tax_table
tax_table <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/tax_table2_ITS.csv"), row.names = 1)
tax_table <- as.matrix(tax_table)

#phylogenetic tree
load(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/trees.Rdata"))

#metadata
metadata <- read_excel(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/metadata_2306.xlsx"), 
                       sheet = "Sheet1")
metadata <- column_to_rownames(metadata, var = "Sample_Name")
metadata$cloneID <- as.factor(metadata$cloneID)
metadata$population <- as.factor(metadata$population)
metadata$site <- as.factor(metadata$site)
metadata$date <- as.factor(metadata$date)
```

##phyloseq object

```{r}
ps <- phyloseq(otu_table(df_rarefied, taxa_are_rows = FALSE), 
               tax_table(tax_table), 
               phy_tree(tree_rarefied2$data), 
               sample_data(metadata))

#extract Kawatabi data
ps_K <- subset_samples(ps, site == "Kawatabi")
#omit AZ_040_1 and OK_037_1 since they distort the NMDS plot
ps_K <- subset_samples(ps_K, !(samplename %in% c("AZ_040_1", "OK_037_1")))
```

##revised BVOC data

```{r import}
#read VOC data
load(file = paste0(path_out, "/data/Sugi/BVOC/exp_Terpene_2209to2408_LODrev_nolod.Rdata"))
load(file = paste0(path_out, "/data/Sugi/BVOC/exp_Terpene_2209to2408_LODrev_log.Rdata"))
#exp_Ohta_nolod is the data in which LOD substituted with 0
#exp_Ohta_log is the log-transformed data

#extract the data for June 2023
BVOC_2306 <- exp_Ohta_nolod %>% subset(Month == "2306")
BVOC_2306_log <- exp_Ohta_log %>% subset(Month == "2306")
#microbial samples for AJ_002_1 and AZ_004_1 were not collected, so remove them
#AZ_040_1 distorted the NMDS plot, so remove it
BVOC_2306 <- BVOC_2306 %>% subset(!(treeID %in% c("AJ_002_01", "AZ_004_01", "AZ_040_01")))
BVOC_2306_log <- BVOC_2306_log %>% subset(!(treeID %in% c("AJ_002_01", "AZ_004_01", "AZ_040_01")))

#match the rownames with those of the microbial data
#feature to match the rownames
rowData(BVOC_2306) <- data.frame(rowData(BVOC_2306)) %>%
  mutate(samplename = paste(subpop, IDmid, str_sub(cloneID, 2), sep = "_"))
rowData(BVOC_2306_log) <- data.frame(rowData(BVOC_2306_log)) %>%
  mutate(samplename = paste(subpop, IDmid, str_sub(cloneID, 2), sep = "_"))

rownames(BVOC_2306) <- rownames(sample_data(ps_K)[match(rowData(BVOC_2306)$samplename, 
                                                        sample_data(ps_K)$samplename), 
                                                  "samplename"])
rownames(BVOC_2306_log) <- rownames(sample_data(ps_K)[match(rowData(BVOC_2306_log)$samplename, 
                                                            sample_data(ps_K)$samplename), 
                                                      "samplename"])

#Longifolene is not detected in the June 2023 samples, so remove it
BVOC_2306 <- BVOC_2306[, -which(colnames(BVOC_2306) == "Longifolene")]
BVOC_2306_log <- BVOC_2306_log[, -which(colnames(BVOC_2306_log) == "Longifolene")]

#remove beta-Caryophyllene from the dataframe
bCary <- which("beta-Caryophyllene" == colnames(BVOC_2306_log)) #the column number of beta-Caryophyllene
BVOC_2306_log_rm <- assay(BVOC_2306_log)[, -bCary] #remove beta-Caryophyllene
```

```{r}
#calculate log-transformed total BVOC- and MTs emission
BVOC_2306_total_log <- data.frame(total = log(rowSums(assay(BVOC_2306)), base = 10)) %>%
  rownames_to_column(var = "sampleID")
MT_2306_log <- data.frame(MTs = log(rowSums(assay(BVOC_2306[, BVOC_2306$mol_weight == "Mono"])) + 1, base = 10)) %>%
  rownames_to_column(var = "sampleID")
SQT_2306_log <- data.frame(SQT = log(rowSums(assay(BVOC_2306[, BVOC_2306$mol_weight == "Sesqui"])) + 1, base = 10)) %>%
  rownames_to_column(var = "sampleID")
DT_2306_log <- data.frame(DT = log(rowSums(assay(BVOC_2306[, BVOC_2306$mol_weight == "Di"])) + 1, base = 10)) %>%
  rownames_to_column(var = "sampleID")

#merge BVOC data
all_2306_log <- BVOC_2306_log_rm %>%
  rownames_to_column(var = "sampleID") %>%
  full_join(BVOC_2306_total_log, by = "sampleID") %>%
  full_join(MT_2306_log, by = "sampleID") %>%
  full_join(SQT_2306_log, by = "sampleID") %>%
  full_join(DT_2306_log, by = "sampleID")
```

#dist

```{r}
dist_bray <- vegdist(otu_table(ps_K), method = "bray")
dist_UF <- UniFrac(ps_K, weighted = TRUE)
```

#NMDS

```{r}
#explore the smallest stress value
nmds_bray <- bestNMDS(dist_bray)
```

```{r}
stressplot(nmds_bray$nmds)
nmds_bray$nmds$stress
save(nmds_bray, file = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/BVOC/NMDS_bray_ITS_BVOC2306_K.Rdata"))
```

#NMDS_bray

##envfit

```{r envfit}
load(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/BVOC/NMDS_bray_ITS_BVOC2306_K.Rdata"))

#extract the samples for which both microbial and BVOC data are available
mat_ITS <- nmds_bray$nmds$points
mat_ITS_BVOC <- mat_ITS[match(all_2306_log$sampleID, rownames(mat_ITS)), ]

#check if the samplename in the bacterial data and the BVOC data match
all(rownames(mat_ITS_BVOC) == all_2306_log$sampleID)
```

```{r envfit}
set.seed(45)
fit_bray <- envfit(mat_ITS_BVOC, 
                   all_2306_log %>% column_to_rownames(var = "sampleID"))
show(fit_bray)
df_fit_bray <-data.frame(fit_bray$vectors$arrows, 
                         r = fit_bray$vectors$r, 
                         p = fit_bray$vectors$pvals)

bray_score <- scores(fit_bray, display = "vectors")
bray_score <- rownames_to_column(data.frame(bray_score))
bray_score <- data.frame(bray_score, 
                        p = fit_bray$vectors$pvals, 
                        arr_col = rep("grey", nrow(bray_score)))
bray_score$arr_col[bray_score$p < 0.05] <- "black"

bray_signif <- bray_score[bray_score$p < 0.1, ]

save(fit_bray, file = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/analysis/envfit_bray_BVOC_LODrev_K.Rdata"))
write.csv(df_fit_bray, file = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/analysis/envfit_bray_BVOC_LODrev_K.csv"))
```

```{r}
#exclude the samples with <LOD values

#exclude the terpenes with less than 10 of the samples having <LOD values
ter_major <- which(apply(all_2306_log > 0, 2, sum) > 10)

#data.frame for the results
df_fit <- data.frame(terpene = colnames(all_2306_log), 
                     MDS1 = NA, 
                     MDS2 = NA, 
                     r = NA, 
                     p = NA)

#perform envfit for each terpene, excluding 0s(<LOD) in the emission data
for (i in ter_major[-1]) {
  set.seed(45)
  #sampleID of the samples with >LOD values
  id <- which(all_2306_log[, i] > 0)
  #perform envfit with the samples with >LOD values
  fit <- envfit(mat_ITS_BVOC[id, ], 
                all_2306_log[id, i], 
                na.rm = TRUE)
  
  #extract the NMDS coordinates
  df_fit[i, "MDS1"] <- fit$vectors$arrows[1, 1]
  df_fit[i, "MDS2"] <- fit$vectors$arrows[1, 2]
  df_fit[i, "r"] <- fit$vectors$r[1]
  df_fit[i, "p"] <- fit$vectors$pvals[1]
}

show(df_fit)
write.csv(df_fit, file = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/analysis/envfit_bray_BVOC_LODrev_omitLOD_K.csv"))
```

```{r}
df_nmds <- data.frame(mat_ITS_BVOC) %>% 
  rownames_to_column(var = "sampleID") %>%
  left_join(data.frame(sample_data(ps_K)) %>% rownames_to_column(var = "sampleID"), by = "sampleID")
col_pop <- colorRampPalette(c("blue3", "orange2"))(3)

p_bray <- ggplot(df_nmds, mapping = aes(x = MDS1, y = MDS2)) +
  theme_classic() + 
  geom_point(data = df_nmds, mapping = aes(colour = population), size = 1) +
  coord_fixed(ratio = 1) + ## need aspect ratio of 1!
  scale_color_manual(values = col_pop, labels = c("Ajigazawa", "Azouji", "Yakushima")) +
  labs(color = "Population") +
  xlim(c(-1.5, 1.3)) + ylim(c(-1.2, 1.3)) +
  
  #arrows to show the direction of BVOC emission vectors
  geom_segment(data = bray_signif,
               aes(x = 0, xend = MDS1, y = 0, yend = MDS2),
               arrow = arrow(length = unit(1, "mm")), 
               color = bray_signif$arr_col) +
  geom_text(data = bray_signif,  
            aes(x = MDS1, y = MDS2 - 0.05, label = rowname), 
            size = 2) +
  
  #annotation to show the significance of BVOC emission vectors
  geom_segment(data = data.frame(x = 0.25, y = -1),
               aes(x = x, xend = (x + 0.2), y = y, yend = y),
               arrow = arrow(length = unit(1, "mm")), 
               color = "grey") +
  annotate("text", 
           x = 0.75, y = -1, size = 2, 
           label = "P < 0.1") +
  
  #annotation to show the stress value
  annotate("text", 
           x = 0.5, y = -1.15, size = 2, 
           label = paste0("stress = ", 
                          round(nmds_bray$nmds$stress, digits = 4))) +
  
  theme(axis.title.x = element_text(size = 7), 
        axis.text.x = element_text(size = 5), 
        
        axis.title.y = element_text(size = 7), 
        axis.text.y = element_text(size = 5), 
        
        axis.line = element_line(linewidth = 0.4), 
        legend.title = element_text(size = 8), 
        legend.text = element_text(size = 7), 
        legend.key.size = unit(2, "mm"))
show(p_bray)
#ggsave(plot = p_bray, 
#       filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/figures/envfit_BVOC_log_LODrev.png"), 
#       dpi = 400, width = 75, height = 75, units = "mm")
```
