---
title: "envfit_ASV_ITS"
output: html_document
date: "2024-10-10"
---

#load packages

```{r}
library(readxl)
library(phyloseq)
library(tidyverse)
library(vegan)
library(RColorBrewer)
```

#path to raw-data directory (change "path" to your raw-data directory)

```{r}
#create "path" file, and define "path" as your raw-data directory(character vector) in the file
#"path" is raw-data directory, and "path_out" is output file directory

source("../scripts/path.R")
```

#source codes

```{r}
source("../R/occurrence.R")
```

#read processed data

```{r import}
#the microbiome outlier (AZ_040_1, based on bray) is excluded in advance
#rarefied-ASV table
df_rarefied <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/BVOC/df_rarefied_ITS_BVOC.csv"), row.names = 1)
rownames(df_rarefied) <- formatC(as.numeric(rownames(df_rarefied)), width = 4, flag = "0") 
#add 0 to the head of rownames

#tax_table
tax_table <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/tax_table2_ITS.csv"), row.names = 1)
tax_table <- as.matrix(tax_table)

#phylogenetic tree
load(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/trees.Rdata"))

#metadata
metadata <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/BVOC/metadata_ITS_BVOC.csv"), row.names = 1)
rownames(metadata) <- formatC(as.numeric(rownames(metadata)), width = 4, flag = "0")

metadata$cloneID <- as.factor(metadata$cloneID)
metadata$population <- as.factor(metadata$population)
metadata$site <- as.factor(metadata$site)
metadata$date <- as.factor(metadata$date)

#log-transformed BVOCs Emission
load(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/BVOC/BVOC_2306_ITS_log.Rdata"))

#output of NMDS (based on bray-curtis dissimilarity)
load(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/BVOC/NMDS_bray_ITS_BVOC2306.Rdata"))

#output of vector-fitting (BVOC on NMDS based on bray)
load(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/analysis/envfit_bray_BVOC.Rdata"))
```

#envfit_BVOC

```{r envfit}
bray_score <- scores(fit_bray, display = "vectors")
bray_score <- rownames_to_column(data.frame(bray_score))
bray_score <- data.frame(bray_score, 
                        p = fit_bray$vectors$pvals, 
                        arr_col = rep("grey", nrow(bray_score)))
bray_score$arr_col[bray_score$p < 0.05] <- "black"

bray_signif <- bray_score[bray_score$p < 0.05, ]
```

#merge at Class level

```{r}
ps <- phyloseq(otu_table(df_rarefied, taxa_are_rows = FALSE), 
               tax_table(tax_table), 
               phy_tree(tree_rarefied2$data), 
               sample_data(metadata))

#merge ASVs at Class level
ps_Class <- tax_glom(ps, taxrank = "Class")
```

```{r}
plot(log(apply(otu_table(ps_Class) / rowSums(otu_table(ps_Class)), 2, mean)), 
     apply(otu_table(ps_Class), 2, occurrence), 
     xlab = "log(Mean Relative Abundance)", 
     ylab = "Occupancy")
abline(h = 2, col = "red")

#cut off Classes whose occurrence is less than 2
Class_abundant <- otu_table(ps_Class)[, which(apply(otu_table(ps_Class), 2, occurrence) > 1)]
```

##envfit_Class

```{r}
set.seed(56)
fit_ASV <- envfit(nmds_bray$nmds, Class_abundant)
fit_ASV$tax_table <- tax_table(ps_Class)
show(fit_ASV)
df_fit_ASV <-data.frame(tax_table(ps_Class)[rownames(fit_ASV$vectors$arrows), "Class"], 
                        fit_ASV$vectors$arrows, 
                        r = fit_ASV$vectors$r, 
                        p = fit_ASV$vectors$pvals)

save(fit_ASV, file = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/analysis/envfit_bray_ASV_BVOC.Rdata"))
write.csv(df_fit_ASV, file = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/analysis/envfit_bray_ASV_BVOC.csv"))
```

```{r}
load(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/analysis/envfit_bray_ASV_BVOC.Rdata"))

ASV_score <- scores(fit_ASV, display = "vectors")
ASV_score <- rownames_to_column(data.frame(ASV_score))
ASV_score <- data.frame(ASV_score, 
                        class = fit_ASV$tax_table[ASV_score$rowname, "Class"], 
                        p = fit_ASV$vectors$pvals, 
                        arr_col = rep("grey", nrow(ASV_score)))

ASV_signif <- ASV_score[ASV_score$p < 0.05, ]
```


```{r}
df_nmds <- data.frame(metadata, nmds_bray$nmds$points)
col_pop <- colorRampPalette(c("blue3", "orange2"))(3)

p_bray <- ggplot(df_nmds, mapping = aes(x = MDS1, y = MDS2)) +
  theme_classic() + 
  geom_point(data = df_nmds, mapping = aes(colour = population), size = 1) +
  coord_fixed(ratio = 1) + ## need aspect ratio of 1!
  scale_color_manual(values = col_pop, labels = c("Ajigazawa", "Azouji", "Yakushima")) +
  labs(color = "Population") +
  xlim(c(-1.2, 1.3)) + ylim(c(-1.2, 1.3)) +
  
  #arrows to show the direction of Class abundance vectors
  geom_segment(data = ASV_signif,
               aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
               arrow = arrow(length = unit(1, "mm")), 
               color = ASV_signif$arr_col) +
  geom_text(data = ASV_signif,  
            aes(x = NMDS1, y = NMDS2, label = Class), 
            size = 1.7) +
  
  #arrows to show the direction of BVOC emission vectors
  geom_segment(data = bray_signif,
               aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
               arrow = arrow(length = unit(1, "mm")), 
               color = "purple3") +
  geom_text(data = bray_signif,  
            aes(x = NMDS1 + 0.15, y = NMDS2 - 0.15, label = rowname), 
            size = 2, color = "purple3") +
  
  #annotation to show the significance
  geom_segment(data = data.frame(x = 0.25, y = -1),
               aes(x = x, xend = (x + 0.2), y = y, yend = y),
               arrow = arrow(length = unit(1, "mm")), 
               color = "purple3") +
  annotate("text", 
           x = 0.75, y = -1.0, size = 2, 
           label = "P < 0.05") +
  
  #annotation to show the stress value
  annotate("text", 
           x = 0.53, y = -1.15, size = 2, 
           label = paste0("stress = ", 
                          round(nmds_bray$nmds$stress, digits = 4))) +
  
  theme(axis.title.x = element_text(size = 7), 
        axis.text.x = element_text(size = 5), 
        
        axis.title.y = element_text(size = 7), 
        axis.text.y = element_text(size = 5), 
        
        axis.line = element_line(linewidth = 0.4), 
        legend.title = element_text(size = 8), 
        legend.text = element_text(size = 7), 
        legend.key.size = unit(2, "mm"))
show(p_bray)
ggsave(plot = p_bray, filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/figures/envfit_BVOC_ASV_log.png"), 
       dpi = 400, width = 75, height = 75, units = "mm")
```
