---
title: "FUNGuild_prep"
output: html_document
date: "2025-07-07"
---

```{r}
library(readxl)
library(tidyverse)
library(qiime2R)
library(phyloseq)
```

#path

```{r}
#create "path" file, and define "path" as your raw-data directory(character vector) in the file
#"path" is raw-data directory, and "path_out" is output file directory
source("../scripts/path.R")
```

#source codes

```{r}
source("../R/add_NA.R")
```

#import raw-data

```{r import}
#rarefied_ASV_table
df_ITS <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/df_rarefied_ITS.csv"), row.names = 1)
rownames(df_ITS) <- formatC(as.numeric(rownames(df_ITS)), width = 4, flag = "0") #add 0 to rownames
otu_ITS <- otu_table(t(df_ITS), taxa_are_rows = TRUE)

#tax_table
tax_ITS <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/tax_table_ITS.csv"), row.names = 1)
tax_ITS <- as.matrix(tax_ITS)
tax_ITS2 <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/tax_table2_ITS.csv"), row.names = 1)
tax_ITS2 <- as.matrix(tax_ITS2)


#phylogenetic tree
load(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/trees.Rdata"))
treeITS <- tree2
treeITS_rarefied <- tree_rarefied2
rm(list = c("tree2", "tree_rarefied2"))

#metadata
metadata <- read_excel(paste0(path_out, "/data/Sugi/metadata_2306.xlsx"), sheet = "Sheet1")
metadata <- column_to_rownames(metadata, var = "Sample_Name")
metadata$cloneID <- as.factor(metadata$cloneID)
metadata$population <- as.factor(metadata$population)
metadata$site <- as.factor(metadata$site)
metadata$date <- as.factor(metadata$date)

#read climate data
meta_pop <- read.csv(paste0(path_out, "/data/Sugi/pop_climate_pca.csv"))
meta_pop <- column_to_rownames(meta_pop, var = "X")

#add climatic data
metadata <- metadata %>%
  dplyr::select(-c(fullname, latitude, longitude, altitude)) %>%
  left_join(meta_pop, by = "population")
rownames(metadata) <- formatC(as.numeric(rownames(metadata)), width = 4, flag = "0")

#classification with confidence
taxonomy <- read_qza(paste0(path, 
                            "/Analysis/taxa/classification_ITS_single_all.qza"))

```

```{r}
#load guild data
path_gs <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/analysis/pathogen_Gs.csv"))
path_gs <- column_to_rownames(path_gs, var = "X")
load(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/phyloseq_pathogen.Rdata"))
```

#phyloseq object

```{r}
ps_ITS <- phyloseq(otu_table = otu_table(otu_ITS, taxa_are_rows = TRUE), 
                   tax_table = tax_table(tax_ITS2), 
                   phy_tree = treeITS_rarefied$data,
                   sample_data = sample_data(metadata))

#extract ASVs whose genus is in the Kobayashi data
ps_Kobayashi <- subset_taxa(ps_ITS, Genus %in% path_gs$Genus)
```

#otu_table for FUNGuild assignment

```{r}
#taxonomy data with consensus values
tax_data <- taxonomy$data
tax_data <- tax_data %>%
  dplyr::mutate(ASV = tax_ITS[sapply(tax_data$Feature.ID, 
                                     charmatch, 
                                     rownames(tax_ITS)), 
                              "ASV_name"]) %>%
  dplyr::mutate(taxonomy = paste(Consensus * 100, "%", ASV, Taxon, sep = "|")) #paste taxonomy with consensus values
```


```{r}
#otu_table for FUNGuild assignment
otu_ITS_FUNGuild <- otu_table(ps_Kobayashi)
colnames(otu_ITS_FUNGuild) <- paste0("sample", colnames(otu_ITS_FUNGuild))
otu_ITS_FUNGuild <- data.frame(otu_ITS_FUNGuild) %>%
  rownames_to_column(var = "ASV") %>%
  left_join((tax_data %>% dplyr::select(ASV, taxonomy)), by = "ASV") #add taxonomy to otu table
```

#write otu_table for FUNGuild assignment

```{r}
write_tsv(otu_ITS_FUNGuild, 
          file = paste0(path_out, 
                   "/231202_Sugi_phyllosphere_June_ITS/processed_data/FUNGuild/otu_table_Kobayashi.tsv"))
```

