---
title: "NMDS"
output: html_document
date: "2024-10-10"
---

#load packages

```{r}
library(readxl)
library(phyloseq)
library(tidyverse)
library(vegan)
library(gridExtra)
library(grid)
library(gtable)
library(ggnewscale)
```

#path to raw-data directory (change "path" to your raw-data directory)

```{r}
#create "path" file, and define "path" as your raw-data directory(character vector) in the file
#"path" is raw-data directory, and "path_out" is output file directory

source("../scripts/path.R")
```

#source codes

```{r}
source("../R/occurrence.R")
source("../R/label.R")
```

#read processed data
##16S

```{r import}
#rarefied_ASV_table
df_16S <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/processed_data/df_rarefied_16S.csv"), row.names = 1)
rownames(df_16S) <- formatC(as.numeric(rownames(df_16S)), width = 4, flag = "0") #add 0 to rownames

#tax_table
tax_16S <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/processed_data/tax_table2_16S.csv"), row.names = 1)
tax_16S <- as.matrix(tax_16S)

#phylogenetic tree
load(paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/processed_data/trees.Rdata"))
tree16S <- tree2
tree16S_rarefied <- tree_rarefied2
rm(list = c("tree2", "tree_rarefied2"))

#load nmds output
load(paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/processed_data/NMDS_bray_16S.Rdata"))
nmds_16S <- nmds_bray
rm(nmds_bray)

load(paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/processed_data/NMDS_weightedUF_16S.Rdata"))
nmds_16S_UF <- nmds_UF
rm(nmds_UF)

load(paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/processed_data/NMDS_unweightedUF_16S.Rdata"))
nmds_16S_unUF <- nmds_unUF
rm(nmds_unUF)
```

##ITS

```{r}
#rarefied_ASV_table
df_ITS <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/df_rarefied_ITS.csv"), row.names = 1)
rownames(df_ITS) <- formatC(as.numeric(rownames(df_ITS)), width = 4, flag = "0") #add 0 to rownames

#tax_table
tax_ITS <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/tax_table2_ITS.csv"), row.names = 1)
tax_ITS <- as.matrix(tax_ITS)

#phylogenetic tree
load(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/trees.Rdata"))
treeITS <- tree2
treeITS_rarefied <- tree_rarefied2
rm(list = c("tree2", "tree_rarefied2"))

#load nmds output
load(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/NMDS_bray_ITS.Rdata"))
nmds_ITS <- nmds_bray
rm(nmds_bray)

load(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/NMDS_weightedUF_ITS.Rdata"))
nmds_ITS_UF <- nmds_UF
rm(nmds_UF)

load(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/NMDS_unweightedUF_ITS.Rdata"))
nmds_ITS_unUF <- nmds_unUF
rm(nmds_unUF)
```

##metadata

```{r}
#metadata
metadata <- read_excel(paste0(path_out, "/data/Sugi/metadata_2306.xlsx"), sheet = "Sheet1")
metadata <- column_to_rownames(metadata, var = "Sample_Name")
metadata$cloneID <- as.factor(metadata$cloneID)
metadata$population <- as.factor(metadata$population)
metadata$site <- as.factor(metadata$site)
metadata$date <- as.factor(metadata$date)

#population metadata
meta_pop <- read_excel(paste0(path_out, "/data/Sugi/metadata_2306.xlsx"), sheet = "location")

#result of PCA on climatic variables
load(paste0(path_out, "/data/Sugi/pca_climate.Rdata"))
df_pcaclim <- data.frame(pca_clim$x)
colnames(df_pcaclim) <- paste0(colnames(df_pcaclim), "_clim")

#merge population metadata and PCA result
meta_pop <- cbind(meta_pop, df_pcaclim)

metadata$PC1 <- meta_pop$PC1_clim[sapply(metadata$fullname, charmatch, meta_pop$fullname)]
metadata$PC2 <- meta_pop$PC2_clim[sapply(metadata$fullname, charmatch, meta_pop$fullname)]
```

#phyloseq object

```{r phyloseq}
ps_16S <- phyloseq(otu_table(df_16S, taxa_are_rows = FALSE), 
               tax_table(tax_16S), 
               phy_tree(tree16S_rarefied$data), 
               sample_data(metadata))

ps_ITS <- phyloseq(otu_table(df_ITS, taxa_are_rows = FALSE), 
               tax_table(tax_ITS), 
               phy_tree(treeITS_rarefied$data), 
               sample_data(metadata))
```

#theme_settings

```{r}
#theme settings
theme_pt <-theme(text = element_text(color = "black"), 
                 axis.text = element_text(color = "black"),
                 
                 legend.key.size = unit(9, "pt"), 
                 legend.spacing.x = unit(0, "mm"), 
                 NULL)
```

#Bray

##16S

```{r}
df_nmds_16S <- data.frame(metadata, nmds_16S$nmds$points)

p_16S <- ggplot() +
  geom_point(data = df_nmds_16S[df_nmds_16S$site == "Tsukuba", ], 
             mapping = aes(x = MDS1, y = MDS2, color = PC1)) +
  scale_color_continuous(low = "#ffa50040", high = "#ffa500FF") +
  labs(color = "Climatic PC1") +
  new_scale_color() +
  geom_point(data = df_nmds_16S[df_nmds_16S$site == "Kawatabi", ], 
             mapping = aes(x = MDS1, y = MDS2, color = PC1)) +
  scale_color_continuous(low = "#19197040", high = "#191970FF") +
  labs(color = "Climatic PC1") +
  
  #theme and plot range
  theme_classic(base_size = 12) + theme_pt +
  coord_fixed(1) +
  xlim(-2, 2) + ylim(-2, 2) +
  
  #stress value
  annotate("text", 
           x = 1.35, y = -2, size = 8 * .352777778, 
           label = paste0("Stress = ", 
                          round(nmds_16S$nmds$stress, digits = 4)))

show(p_16S)

ggsave(filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/figures/NMDS_bray_wide.png"), 
       plot = p_16S, 
       dpi = 300, width = 160, height = 160, units = "mm")
```

```{r, echo=FALSE}
p_16S <- ggplot(data = df_nmds_16S, 
                 mapping = aes(x = MDS1, y = MDS2, color = clade)) +
  theme_classic(base_size = 12) +
  coord_fixed(1) +
  xlim(-2, 2) + ylim(-2, 2) +
  geom_point() +
  scale_color_viridis_d() +
  theme_pt + labs(color = "Clade") +
  annotate("text", 
           x = 1.35, y = -2, size = 8 * .352777778, 
           label = paste0("Stress = ", 
                          round(nmds_16S$nmds$stress, digits = 4)))

p_16S
ggsave(filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/figures/NMDS_bray_clade.png"), 
       plot = p_16S, 
       dpi = 300, width = 160, height = 160, units = "mm")
```

###envfit(ASV)

```{r}
#import the result of vectorfitting of Phylum abundance on NMDS plot
load(paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/analysis/envfit_bray_ASV.Rdata"))

score_16S <- scores(fit_ASV_16S, display = "vectors")
score_16S <- rownames_to_column(data.frame(score_16S))
score_16S <- data.frame(score_16S, 
                        class = fit_ASV_16S$tax_table[score_16S$rowname, "Phylum"], 
                        p = fit_ASV_16S$vectors$pvals, 
                        arr_col = rep("grey", nrow(score_16S)))

signif_16S <- score_16S[score_16S$p < 0.05, ]
```

```{r}
#NMDS plot with bacterial abundance arrows
p_16S_ASV <- ggplot(data = df_nmds_16S, 
                 mapping = aes(x = MDS1, y = MDS2, color = fac_sipop))
p_16S_ASV <- p_16S_ASV + theme_classic()
p_16S_ASV <- p_16S_ASV + coord_fixed(1)
p_16S_ASV <- p_16S_ASV + xlim(-2, 2) + ylim(-2, 2)
p_16S_ASV <- p_16S_ASV + scale_color_manual(values = col_sipop)
p_16S_ASV <- p_16S_ASV + geom_point()
p_16S_ASV <- p_16S_ASV + theme(legend.position = "none")
p_16S_ASV <- p_16S_ASV + theme_pt

#show bacterial abundance arrows(only significantly correlated)
p_16S_ASV <- p_16S_ASV + geom_segment(data = signif_16S,
                                      aes(x = 0, xend = NMDS1 * 1.5, y = 0, yend = NMDS2 * 1.5),
                                      arrow = arrow(length = unit(2.5, "mm")), 
                                      color = signif_16S$arr_col) +
  geom_text(data = signif_16S,  
            aes(x = NMDS1 * 1.5, y = NMDS2 * 1.5, label = Phylum), 
            size = 7 * .352777778, color = "black")

#stress value
p_16S_ASV <- p_16S_ASV + annotate("text", x = 1.35, y = -2, size = 7 * .352777778, 
                                  label = paste0("Stress = ", 
                                                 round(nmds_16S$nmds$stress, digits = 4)))

ggsave(filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/figures/NMDS_bray_ASV.png"), 
       plot = p_16S_ASV, 
       dpi = 300, width = 160, height = 160, units = "mm")
```

##ITS

```{r}
df_nmds_ITS <- data.frame(metadata, nmds_ITS$nmds$points)

p_ITS <- ggplot() +
  geom_point(data = df_nmds_ITS[df_nmds_ITS$site == "Tsukuba", ], 
             mapping = aes(x = MDS1, y = MDS2, color = PC1)) +
  scale_color_continuous(low = "#ffa50040", high = "#ffa500FF") +
  labs(color = "Climatic PC1") +
  new_scale_color() +
  geom_point(data = df_nmds_ITS[df_nmds_ITS$site == "Kawatabi", ], 
             mapping = aes(x = MDS1, y = MDS2, color = PC1)) +
  scale_color_continuous(low = "#19197040", high = "#191970FF") +
  labs(color = "Climatic PC1") +
  
  #theme and plot range
  theme_classic(base_size = 12) + theme_pt +
  coord_fixed(1) +
  xlim(-2.5, 2) + ylim(-2, 2.5) +
  
  #stress
  annotate("text", 
           x = 1.3, y = -2, size = 8 * .352777778, 
           label = paste0("Stress = ", 
                          round(nmds_ITS$nmds$stress, digits = 4)))

show(p_ITS)

ggsave(filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/figures/NMDS_bray_wide.png"), 
       plot = p_ITS, 
       dpi = 300, width = 160, height = 160, units = "mm")
```

```{r, echo=FALSE}
p_ITS <- ggplot(data = df_nmds_ITS, 
                 mapping = aes(x = MDS1, y = MDS2, color = clade)) +
  theme_classic() + theme_pt +
  coord_fixed(1) +
  xlim(-2.5, 2) + ylim(-2, 2.5) +
  scale_color_viridis_d() +
  geom_point() + labs(color = "Clade") +
  
  #stress
  annotate("text", 
           x = 1.5, y = -2, size = 7 * .352777778, 
           label = paste0("Stress = ", 
                          round(nmds_ITS$nmds$stress, digits = 4)))
p_ITS

ggsave(filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/figures/NMDS_bray_clade.png"), 
       plot = p_ITS, 
       dpi = 300, width = 160, height = 160, units = "mm")
```

###envfit(ASV)

```{r}
#import the result of vectorfitting of Class abundance on NMDS plot
load(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/analysis/envfit_bray_ASV.Rdata"))

score_ITS <- scores(fit_ASV_ITS, display = "vectors")
score_ITS <- rownames_to_column(data.frame(score_ITS))
score_ITS <- data.frame(score_ITS, 
                        class = fit_ASV_ITS$tax_table[score_ITS$rowname, "Class"], 
                        p = fit_ASV_ITS$vectors$pvals, 
                        arr_col = rep("grey", nrow(score_ITS)))

signif_ITS <- score_ITS[score_ITS$p < 0.05, ]
```

```{r}
#NMDS plot with fungal abundance arrows
df_nmds_ITS <- data.frame(metadata, nmds_ITS$nmds$points)

p_ITS_ASV <- ggplot(data = df_nmds_ITS, 
                 mapping = aes(x = MDS1, y = MDS2, color = fac_sipop))
p_ITS_ASV <- p_ITS_ASV + theme_classic()
p_ITS_ASV <- p_ITS_ASV + coord_fixed(1)
p_ITS_ASV <- p_ITS_ASV + xlim(-2.5, 2) + ylim(-2, 2.5)
p_ITS_ASV <- p_ITS_ASV + scale_color_manual(values = col_sipop)
p_ITS_ASV <- p_ITS_ASV + geom_point()
p_ITS_ASV <- p_ITS_ASV + theme_pt

p_ITS_ASV <- p_ITS_ASV + theme(legend.position = "none")

#show fungal abundance arrows(only sigunificantly correlated
p_ITS_ASV  <- p_ITS_ASV + geom_segment(data = signif_ITS,
                                       aes(x = 0, xend = NMDS1 * 1.5, y = 0, yend = NMDS2 * 1.5),
                                       arrow = arrow(length = unit(2.5, "mm")), 
                                       color = signif_ITS$arr_col) +
  geom_text(data = signif_ITS, 
            aes(x = NMDS1 * 1.5, y = NMDS2 * 1.5, label = Class),
            size = 7 * .352777778, color = "black")

#stress value
p_ITS_ASV <- p_ITS_ASV + annotate("text", 
                                  x = 1.5, y = -2, size = 7 * .352777778, 
                                  label = paste0("Stress = ",
                                                 round(nmds_ITS$nmds$stress, digits = 4)))

ggsave(filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/figures/NMDS_bray_ASV.png"), 
       plot = p_ITS_ASV, 
       dpi = 300, width = 160, height = 160, units = "mm")
```

##legend

```{r}
p_legend <- ggplot(data = df_nmds_16S, 
                 mapping = aes(x = MDS1, y = MDS2, color = site))
p_legend <- p_legend + theme_classic()
p_legend <- p_legend + coord_fixed(1)
p_legend <- p_legend + scale_color_manual(values = c("blue", "orange3"))
p_legend <- p_legend + geom_text(aes(label = names(pop_num)), size = 6)
p_legend <- p_legend + labs(color = "Site")
p_legend <- p_legend + theme(legend.position = "inside", 
                       legend.title = element_text(size = 7.5), 
                       legend.text = element_text(size = 5), 
                       legend.key.size = unit(1, "mm"))
p_legend
legend <- gtable_filter(ggplotGrob(p_legend), "guide-box")

ggsave(grid.arrange(legend), 
       filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/figures/NMDS_legend.png"), 
       dpi = 400, width = 30, height = 30, units = "mm")
```

##layout two plots

```{r}
pl_16S <- p_16S + theme(legend.position = "bottom")
legend <- gtable_filter(ggplotGrob(pl_16S), "guide-box")
pl_16S <- pl_16S + theme(legend.position = "none")
pl_ITS <- p_ITS + theme(legend.position = "none")

pl_16S <- arrangeGrob(pl_16S, top = create_label("A"))
pl_ITS <- arrangeGrob(pl_ITS, top = create_label("B"))

layout <- rbind(c(1,2), c(3,3))

p_two_bray <- grid.arrange(pl_16S, pl_ITS, legend, 
                           layout_matrix = layout, widths = c(1, 1), heights = c(9, 1))

ggsave(p_two_bray, filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/figures/NMDS_bray_both1.pdf"), 
       dpi = 300, width = 160, height = 90, units = "mm", scale = 1)

#p_two_bray_ASV <- ggarrange(p_16S_ASV, p_ITS_ASV, nrow = 1, ncol = 2, 
#                            labels = letters[1:2], 
#                            font.label = list(size = 7, color = "black", face = "bold"))
#ggsave(p_two_bray_ASV, filename = paste0(path_out, #"/231202_Sugi_phyllosphere_June_16S/figures/NMDS_bray_both_ASV.png"), 
#       dpi = 400, width = 160, height = 80, units = "mm", scale = 1)
```

#UniFrac
##16S
```{r}
df_nmds_16S_UF <- data.frame(metadata, nmds_16S_UF$nmds$points)

p_16S_UF <- ggplot(data = df_nmds_16S_UF, 
                 mapping = aes(x = MDS1, y = MDS2, color = fac_sipop))
p_16S_UF <- p_16S_UF + theme_classic()
p_16S_UF <- p_16S_UF + coord_fixed(1)
p_16S_UF <- p_16S_UF + xlim(-0.15, 0.1) + ylim(-0.15, 0.1)
p_16S_UF <- p_16S_UF + scale_color_manual(values = col_sipop)
p_16S_UF <- p_16S_UF + geom_point()
p_16S_UF <- p_16S_UF + annotate("text", 
                                x = 0.05, y = -0.15,
                                label = paste0("stress = ", 
                                               round(nmds_16S_UF$nmds$stress, digits = 5)))
p_16S_UF <- p_16S_UF + theme(legend.position = "none")
p_16S_UF
ggsave(filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/figures/NMDS_UF.png"), 
       plot = p_16S_UF, dpi = 400, width = 150, height = 150, units = "mm")
```

##ITS

```{r}
df_nmds_ITS_UF <- data.frame(metadata, nmds_ITS_UF$nmds$points)

p_ITS_UF <- ggplot(data = df_nmds_ITS_UF, 
                 mapping = aes(x = MDS1, y = MDS2, color = fac_sipop)) + 
  theme_classic() + 
  coord_fixed(1) + 
  xlim(-0.12, 0.04) + ylim(-0.08, 0.08) + 
  scale_color_manual(values = col_sipop) + 
  geom_point() + 
  annotate("text", x = 0.015, y = -0.08,
           label = paste0("stress = ", 
                          round(nmds_ITS_UF$nmds$stress, digits = 5))) + 
  theme(legend.position = "none")
p_ITS_UF
ggsave(filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/figures/NMDS_UF.png"), 
       plot = p_ITS_UF, dpi = 400, width = 150, height = 150, units = "mm")
```

#layout two plots(UF)

```{r}
p_16SUF_label <- arrangeGrob(p_16S_UF, top = create_label("a"))
p_ITSUF_label <- arrangeGrob(p_ITS_UF, top = create_label("b"))

p_two_UF <- grid.arrange(p_16SUF_label, p_ITSUF_label, nrow = 1)
ggsave(p_two_UF, filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/figures/NMDS_UF_both.png"), 
       dpi = 400, width = 150, height = 75, units = "mm", scale = 1)
```

#unweighted UF
##16S

```{r}
df_nmds_16S_unUF <- data.frame(metadata, nmds_16S_unUF$nmds$points)

p_16S_UF <- ggplot(data = df_nmds_16S_unUF, 
                 mapping = aes(x = MDS1, y = MDS2, color = fac_sipop))
p_16S_UF <- p_16S_UF + theme_classic()
p_16S_UF <- p_16S_UF + coord_fixed(1)
p_16S_UF <- p_16S_UF + xlim(-0.27, 0.77) + ylim(-0.52, 0.52)
p_16S_UF <- p_16S_UF + scale_color_manual(values = col_sipop)
p_16S_UF <- p_16S_UF + geom_point()
p_16S_UF <- p_16S_UF + annotate("text", 
                                x = 0.63, y = -0.5,
                                label = paste0("stress = ", 
                                               round(nmds_16S_unUF$nmds$stress, digits = 5)))
p_16S_UF <- p_16S_UF + theme(legend.position = "none")
p_16S_UF

ggsave(filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/figures/NMDS_unweightedUF.png"), 
       plot = p_16S_UF, dpi = 400, width = 150, height = 150, units = "mm")
```

##ITS

```{r}
df_nmds_ITS_unUF <- data.frame(metadata, nmds_ITS_unUF$nmds$points)

p_ITS_UF <- ggplot(data = df_nmds_ITS_unUF, 
                 mapping = aes(x = MDS1, y = MDS2, color = fac_sipop)) + 
  theme_classic() + 
  coord_fixed(1) + 
  xlim(-0.52, 0.52) + ylim(-0.52, 0.52) +
  scale_color_manual(values = col_sipop) + 
  geom_point() + 
  annotate("text", x = 0.4, y = -0.5,
           label = paste0("stress = ", 
                          round(nmds_ITS_unUF$nmds$stress, digits = 5))) + 
  theme(legend.position = "none")
p_ITS_UF
ggsave(filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/figures/NMDS_unweightedUF.png"),
       plot = p_ITS_UF, dpi = 400, width = 150, height = 150, units = "mm")
```

```{r}
p_16SUF_label <- arrangeGrob(p_16S_UF, top = create_label("a"))
p_ITSUF_label <- arrangeGrob(p_ITS_UF, top = create_label("b"))

p_two_UF <- grid.arrange(p_16SUF_label, p_ITSUF_label, nrow = 1)
ggsave(p_two_UF, filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/figures/NMDS_unweightedUF_both.png"), 
       dpi = 400, width = 150, height = 75, units = "mm", scale = 2)
```

