---
title: "pathogen_Hiura2021_all"
output: html_document
date: "2024-10-10"
---

#load packages

```{r}
#test commit
library(readxl)
library(phyloseq)
library(tidyverse)
library(vegan)
library(glm2)
library(MASS)
library(lmtest)
library(ggfortify)
library(ggeffects)
library(RColorBrewer)
library(gridExtra)
library(grid)
library(gtable)
library(gt)
```

#path to raw-data directory (change "path" to your raw-data directory)

```{r}
#create "path" file, and define "path" as your raw-data directory(character vector) in the file
#"path" is raw-data directory, and "path_out" is output file directory

source("../scripts/path.R")
```

#source codes

```{r}
source("../R/occurrence.R")
source("../R/label.R")
source("../R/Greek.R")
source("../R/html_italic.R")
```

#read processed data
#ITS

```{r import}
#rarefied_ASV_table
df_ITS <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/df_rarefied_ITS.csv"), row.names = 1)
rownames(df_ITS) <- formatC(as.numeric(rownames(df_ITS)), width = 4, flag = "0") #add 0 to rownames

#tax_table
tax_ITS <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/tax_table2_ITS.csv"), row.names = 1)
tax_ITS <- as.matrix(tax_ITS)

#phylogenetic tree
load(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/trees.Rdata"))
treeITS <- tree2
treeITS_rarefied <- tree_rarefied2
rm(list = c("tree2", "tree_rarefied2"))

#metadata
metadata <- read_excel(paste0(path_out, "/data/Sugi/metadata_2306.xlsx"), sheet = "Sheet1")
metadata <- column_to_rownames(metadata, var = "Sample_Name")
metadata$cloneID <- as.factor(metadata$cloneID)
metadata$population <- as.factor(metadata$population)
metadata$site <- as.factor(metadata$site)
metadata$date <- as.factor(metadata$date)

#read climate data
meta_pop <- read.csv(paste0(path_out, "/data/Sugi/pop_climate_pca.csv"))
meta_pop <- column_to_rownames(meta_pop, var = "X")

#add climatic data
metadata <- metadata %>%
  dplyr::select(-c(fullname, latitude, longitude, altitude)) %>%
  left_join(meta_pop, by = "population")
rownames(metadata) <- formatC(as.numeric(rownames(metadata)), width = 4, flag = "0")
```

##for BVOCs

```{r}
#the microbiome outlier (AZ_040_1, based on bray) is excluded in advance
#rarefied-ASV table
df_ITS_ter <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/BVOC/df_rarefied_ITS_BVOC.csv"), row.names = 1)
rownames(df_ITS_ter) <- formatC(as.numeric(rownames(df_ITS_ter)), width = 4, flag = "0") 
#add 0 to the head of rownames

#metadata
meta_ter <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/BVOC/metadata_ITS_BVOC.csv"), row.names = 1)
rownames(meta_ter) <- formatC(as.numeric(rownames(meta_ter)), width = 4, flag = "0")

meta_ter$cloneID <- as.factor(meta_ter$cloneID)
meta_ter$population <- as.factor(meta_ter$population)
meta_ter$site <- as.factor(meta_ter$site)
meta_ter$date <- as.factor(meta_ter$date)

#log-transformed BVOCs Emission
load(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/BVOC/BVOC_2306_ITS_log.Rdata"))
colnames(BVOC_2306_log) <- greek(colnames(BVOC_2306_log))
colnames(BVOC_2306_log) <- html_italic(colnames(BVOC_2306_log), "-")
BVOC_2306_log <- rownames_to_column(BVOC_2306_log, var = "samplename")

#load terpene PCA result
load(paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/processed_data/BVOC/pca_BVOC_2306_16S_log.Rdata"))
pca_BVOC_coor <- data.frame(pca_BVOC_log_rm$x) %>%
  rownames_to_column(var = "samplename")


#merge metadata and BVOC data
meta_ter_pca <- left_join(meta_ter, BVOC_2306_log, by = "samplename") %>%
  left_join(y = pca_BVOC_coor, by = "samplename")
rownames(meta_ter_pca) <- rownames(meta_ter)
```

#pathogen

```{r}
#read pathogen data (Hiura et al. 2021)
path_distr <- read.csv(file = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/pathogens_Hiura2021.csv"))
path_distr <- path_distr %>% select_if(negate(anyNA))
path_distr <- column_to_rownames(path_distr, "Prefecture")

name_spl <- sapply(colnames(path_distr), str_split, "\\.+")

##get pathogen Scinames, split them, make "pathogen" dataframe
pathogen <- data.frame(Genus = sapply(name_spl, `[`, 1), 
                       species = paste0(sapply(name_spl, `[`, 1), "_", sapply(name_spl, `[`, 2)), 
                       full = names(name_spl))
pathogen <- pathogen %>%
  # Add species number within each genus
  group_by(Genus) %>%
  mutate(n_sp = row_number()) %>%
  ungroup()
```

#ps

```{r}
ps_ITS <- phyloseq(otu_table(df_ITS, taxa_are_rows = FALSE), 
               tax_table(tax_ITS), 
               phy_tree(treeITS_rarefied$data), 
               sample_data(metadata))
ps_ITS_ter <- phyloseq(otu_table(df_ITS_ter, taxa_are_rows = FALSE), 
                       tax_table(tax_ITS), 
                       phy_tree(treeITS_rarefied$data), 
                       sample_data(meta_ter))

#agglomerate at Species level
ps_ITS_sp <- tax_glom(ps_ITS, taxrank = "Species")
ps_ITS_ter_sp <- tax_glom(ps_ITS_ter, taxrank = "Species")

#agglomerate at Genus level
ps_ITS_gs <- tax_glom(ps_ITS, taxrank = "Genus")
ps_ITS_ter_gs <- tax_glom(ps_ITS_ter, taxrank = "Genus")
```

#search Species from tax table

```{r}
#search pathogens in phyllosphere microbiome
sp_in <- sapply(pathogen$species, charmatch, ps_ITS_sp@tax_table[, "Species"], nomatch = NA)
sp_in <- sp_in[!is.na(sp_in)]
path_sp <- pathogen[pathogen$species == names(sp_in), ]
#only two species "Sarea_resinae" and "Leptosphaeria_sp" were detected, whose function is unknown


apply(ps_ITS_sp@otu_table[, rownames(ps_ITS_sp@tax_table[sp_in, ])], 2, occurrence)
apply(ps_ITS_sp@otu_table[, rownames(ps_ITS_sp@tax_table[sp_in, ])] > 0, 2, which)
#both species are not consistent nor abundant

path_sp$ASV <- rownames(ps_ITS_sp@tax_table[sp_in, ])
path_sp$occ <- sapply(sapply(apply(ps_ITS_sp@otu_table[, rownames(ps_ITS_sp@tax_table[sp_in, ])] > 0, 2, which), 
                             names), 
                      paste, collapse = "and")
#names of samples in which each species was detected

path_sp

#write.csv(path_sp, file = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/analysis/pathogen_Sp_all.csv"))
```

#search Genus

```{r}
#summarize pathogen data
#some Genus contains two species with different function
path_gs <- pathogen %>%
  # Pivot wider to create species columns
  pivot_wider(
    id_cols = Genus,
    names_from = n_sp,
    values_from = species,
    names_prefix = "species_"
    )
```

```{r}
#positions of pathogens in tax table
gs_in <- sapply(path_gs$Genus, charmatch, ps_ITS_gs@tax_table[, "Genus"], nomatch = NA)
gs_in <- gs_in[!is.na(gs_in)]
#remove NAs

#pathogens detected in the phyllosphere of C. japonica
path_gs[sapply(names(gs_in), charmatch, path_gs$Genus), ]
#47 pathogenic Genera were also in microbiome data
#extract ASV names for these pathogens
gs_asv <- rownames(ps_ITS_gs@tax_table[gs_in, ])
#add ASV name to pathogen list
path_gs$ASV <- NULL
path_gs$ASV[sapply(names(gs_in), grep, path_gs$Genus)] <- gs_asv

#ps object with only Genera which include pathogens
ps_ITS_path <- prune_taxa(gs_asv, ps_ITS_gs)
ps_ITS_ter_path <- prune_taxa(gs_asv, ps_ITS_ter_gs)

#occurrence of each Genus
path_gs$occurrence <- NULL
path_gs$occurrence[sapply(rownames(ps_ITS_path@tax_table), 
                          charmatch, path_gs$ASV)] <- apply(ps_ITS_path@otu_table, 2, occurrence)

#write.csv(path_gs, file = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/analysis/pathogen_Gs_all.csv"))
save(ps_ITS_path, ps_ITS_ter_path, file = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/phyloseq_pathogen_all.Rdata"))
```

#GLM

```{r}
path_gs <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/analysis/pathogen_Gs_all.csv"))
path_gs <- column_to_rownames(path_gs, var = "X")
load(paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/processed_data/phyloseq_pathogen_all.Rdata"))

#show prediction and CI for the model with the total abundance tested on PC1_clim
path_total <- apply(ps_ITS_path@otu_table, 1, sum)
abund_plot <- data.frame(metadata, path_total)
model_p <- glm2(path_total~site + PC1_clim + PC2_clim, 
                data = abund_plot, 
                family = poisson(link = "log"))
summary(model_p)
#climatic PC1 was negatively correlated with the aggregated relative abundance of putative pathogenic fungal genera
#relative abundance of pathogens was lower at Tsukuba

model_nb <- glm.nb(path_total~site + PC1_clim + PC2_clim, 
                   data = abund_plot, 
                   link = "log")
summary(model_nb)
#no variables were detected as significant when negative binomial distribution was used
```

##Residual plot (needed to check the validity of the assumed distribution?)

```{r}
#Check if there is any trend in residual plot
#Any trend in a residual plot indicates a violation of the model assumption?
checkdata <- data.frame(abund_plot, lambda_pred = predict(model_p))
checkdata  <- checkdata %>%
  dplyr::select(PC1_clim, PC2_clim, site, path_total, lambda_pred) %>%
  mutate(log_path = log(path_total + 1), residual = log_path - lambda_pred)

ggplot(data = checkdata, mapping = aes(x = lambda_pred, y = residual)) + 
  geom_point() + theme_classic()

#autoplot shows various plots 
autoplot(model_p)
#samples with high relative abundance of pathogens are not fitted to poisson distribution
```

```{r}
#negative binomial
model_nb <- glm.nb(path_total~site + PC1_clim + PC2_clim, 
                   data = abund_plot, 
                   link = "log")

checknb <- data.frame(abund_plot, lambda_pred = predict(model_nb))
checknb  <- checknb %>%
  dplyr::select(PC1_clim, PC2_clim, site, path_total, lambda_pred) %>%
  mutate(log_path = log(path_total + 1), residual = log_path - lambda_pred)

ggplot(data = checknb, mapping = aes(x = lambda_pred, y = residual)) + 
  geom_point() + theme_classic()

autoplot(model_nb)
#outliers with the high relative abundance of pathogens are well fitted to negative binomial distribution
#zeros are not well fitted to negative binomial distribution
```

##mytheme

```{r}
#theme settings
mytheme <-theme(text = element_text(color = "black"), 
                axis.text = element_text(color = "black"),
                axis.title.y = element_text(size = 8), 
                
                legend.key.size = unit(9, "pt"), 
                legend.spacing.x = unit(0, "mm"))
```

##plot

```{r}
#estimate confidence intervals for model coefficients
##confidence intervals are calculated as 
##low = predict - qnorm(0.975) * predict$se.fit, high = predict + qnorm(0.975) * predict$se.fit
preddata <- ggpredict(model_p, terms = c("PC1_clim", "site"))

p_path <- ggplot(data = abund_plot, 
                 mapping = aes(x = PC1_clim, y = path_total, color = site)) +
  geom_point() +
  scale_color_viridis_d() + 
  geom_line(data = preddata, 
            aes(x = x, y = predicted, color = group), 
            linewidth = 0.4) +
  geom_ribbon(data = preddata, 
              aes(x = x, ymin = conf.low, ymax = conf.high, y = predicted, fill = group),
              alpha = 0.1, linewidth = 0, color = NA) +
  scale_fill_discrete(breaks = "group", name = NULL) +
  theme_classic(base_size = 12) + mytheme +
  xlab("Climatic PC1") + ylab("Abundance of the putative pathogenic fungi after rarefaction") + labs(color = "Site") + NULL
  
show(p_path)

ggsave(filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/figures/pathogen_climate1_All.pdf"), 
       plot = p_path, 
       dpi = 300, width = 160, height = 90, units = "mm")
```

```{r}
preddata2 <- ggpredict(model_p, terms = c("PC2_clim", "site"))

p_path <- ggplot(data = abund_plot, 
                 mapping = aes(x = PC2_clim, y = path_total, color = site)) +
  geom_point() +
  scale_color_viridis_d() + 
  geom_line(data = preddata2, 
            aes(x = x, y = predicted, color = group), 
            linewidth = 0.4) +
  geom_ribbon(data = preddata2, 
              aes(x = x, ymin = conf.low, ymax = conf.high, y = predicted, fill = group),
              alpha = 0.1, linewidth = 0, color = NA) +
  scale_fill_discrete(breaks = "group", name = NULL) +
  theme_classic(base_size = 12) + mytheme +
  xlab("Climatic PC2") + ylab("Abundance of the putative pathogenic fungi after rarefaction") + labs(color = "Site") + NULL
  
show(p_path)

#ggsave(filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_ITS/figures/pathogen_climate2_all.png"), 
#       plot = p_path, 
#       dpi = 300, width = 160, height = 90, units = "mm")
```

#GLM_terpene

```{r}
#show prediction and CI for the model with the total abundance tested on PC1_clim
path_total_ter <- apply(ps_ITS_ter_path@otu_table, 1, sum)
abund_ter <- meta_ter_pca
abund_ter$path_total_ter <- path_total_ter
model_p <- glm2(path_total_ter~PC3, 
                data = abund_ter, 
                family = poisson(link = "log"))
summary(model_p)
#Any variables tend to be detected as significant when a poisson distribution is assumed

model_nb <- glm.nb(path_total_ter~PC3, 
                   data = abund_ter, 
                   link = "log")
summary(model_nb)
#no variables were detected as significant when negative binomial distribution was used
```

```{r}
autoplot(model_p)
autoplot(model_nb)
```


