---
title: "pca_BVOC"
output: html_document
date: "2024-10-10"
---

#load packages

```{r}
library(readxl)
library(phyloseq)
library(tidyverse)
library(vegan)
library(glm2)
library(car)
library(MASS)
library(ggfortify)
library(RColorBrewer)
library(scales)
library(ggrepel)
library(gridExtra)
library(gtable)
library(grid)
library(ggtext)
library(SummarizedExperiment)
```

#path to raw-data directory (change "path" to your raw-data directory)

```{r}
#create "path" file, and define "path" as your raw-data directory(character vector) in the file
#"path" is raw-data directory, and "path_out" is output file directory

source("../scripts/path.R")
```

#source codes

```{r}
source("../R/label.R")
source("../R/html_italic.R")
source("../R/Greek.R")
source("../R/gg_italic.R")
source("../R/round_preserve_lod.R")
```

#read processed data

```{r}
#read VOC data
load(file = paste0(path_out, "/data/Sugi/BVOC/exp_Terpene_2209to2408_LODrev_nolod.Rdata"))
load(file = paste0(path_out, "/data/Sugi/BVOC/exp_Terpene_2209to2408_LODrev_log.Rdata"))

#extract the data for June 2023
BVOC_2306 <- exp_Ohta_nolod %>% subset(Month == "2306")
BVOC_2306_log <- exp_Ohta_log %>% subset(Month == "2306")
#microbial samples for AJ_002_1 and AZ_004_1 were not collected, so remove them
BVOC_2306 <- BVOC_2306 %>% subset(!(treeID %in% c("AJ_002_01", "AZ_004_01")))
BVOC_2306_log <- BVOC_2306_log %>% subset(!(treeID %in% c("AJ_002_01", "AZ_004_01")))

#Longifolene is not detected in the June 2023 samples, so remove it
BVOC_2306 <- BVOC_2306[, -which(colnames(BVOC_2306) == "Longifolene")]
BVOC_2306_log <- BVOC_2306_log[, -which(colnames(BVOC_2306_log) == "Longifolene")]
```

```{r import}
metadata <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/processed_data/BVOC/metadata_16S_BVOC.csv"), row.names = 1)
rownames(metadata) <- formatC(as.numeric(rownames(metadata)), width = 4, flag = "0")

metadata$cloneID <- as.factor(metadata$cloneID)
metadata$population <- as.factor(metadata$population)
metadata$site <- as.factor(metadata$site)
metadata$date <- as.factor(metadata$date)

#population metadata
meta_pop <- read_excel(paste0(path_out, "/data/Sugi/metadata_2306.xlsx"), sheet = "location")

#result of PCA on climatic variables
load(paste0(path_out, "/data/Sugi/pca_climate.Rdata"))
df_pcaclim <- data.frame(pca_clim$x)
colnames(df_pcaclim) <- paste0(colnames(df_pcaclim), "_clim")

#merge population metadata and PCA result
meta_pop <- cbind(meta_pop, df_pcaclim)
```

#theme settings

```{r}
#theme settings
mytheme <-theme(text = element_text(color = "black"), 
                axis.text = element_text(color = "black"), 
                legend.key.size = unit(8, "pt"), 
                legend.spacing.x = unit(0, "mm"))
```

#Barplot of basal emission rate

```{r}
#make the dataframe to draw a barplot
#gather the emission data before plotting
BVOC_2306_ga <- rownames_to_column(assay(BVOC_2306), var = "sampleID")
BVOC_2306_ga <- full_join(BVOC_2306_ga,
                          data.frame(rowData(BVOC_2306)) %>% dplyr::select(sampleID, Population),
                          by = "sampleID")
BVOC_2306_ga <- pivot_longer(BVOC_2306_ga,
                             cols = -c(sampleID, Population),
                             names_to = "BVOC",
                             values_to = "emission")

labeller <- c(AJ = "Ajigasawa", AZ = "Azouji", YK = "Yakushima")

#assign colors to each terpene
col_BVOC <- c(colorRampPalette(c("green2", "grey30", "yellow2"))(12), #MTs
              colorRampPalette(c("purple", "purple3"))(2), #SQTs 
              colorRampPalette(c("skyblue", "blue4"))(2)) #DTs
names(col_BVOC) <- colnames(BVOC_2306)
```

```{r}
#draw barplot
p_BVOC <- ggplot(data = BVOC_2306_ga, mapping = aes(x = sampleID, y = emission, 
                                                    fill = factor(BVOC, 
                                                                  levels = colnames(BVOC_2306))))
p_BVOC <- p_BVOC + geom_bar(stat = "identity")
p_BVOC <- p_BVOC + theme_classic(base_size = 11)
p_BVOC <- p_BVOC + mytheme
p_BVOC <- p_BVOC + scale_fill_manual(values = col_BVOC)
p_BVOC <- p_BVOC + scale_y_continuous(labels = label_comma())
p_BVOC <- p_BVOC + facet_wrap(~ Population, scales = "free_x", 
                              labeller = labeller(Population = labeller))
p_BVOC <- p_BVOC + labs(fill = "Terpenes") +
  ylab(expression(paste("Basal emission rate (ng ", {gdw^-1}, " ", {h^-1}, ")"))) +
  labs()
p_BVOC <- p_BVOC + mytheme + 
  theme(text = element_text(color = "black"), 
        strip.text = element_text(size = 6),
        legend.title = element_text(size = 8), 
        legend.text = element_markdown(size = 7),
        axis.title.x = element_blank(), 
        axis.text.x = element_blank())
show(p_BVOC)

ggsave(plot = p_BVOC, filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/figures/barplot_BVOC_LODrev.pdf"), 
       dpi = 300, width = 160, height = 80, units = "mm")
```

#pca

```{r}
#remove beta-Caryophyllene from dataframe
bCary <- which("beta-Caryophyllene" == colnames(BVOC_2306_log)) #the column number of beta-Caryophyllene

BVOC_2306_log_rm <- assay(BVOC_2306_log)[, -bCary] #remove beta-Caryophyllene

pca_BVOC_log_rm_LODrev <- prcomp(BVOC_2306_log_rm, 
                          scale. = TRUE)
summary(pca_BVOC_log_rm_LODrev)

save(pca_BVOC_log_rm_LODrev, file = paste0(path_out, "/data/Sugi/BVOC/pca_BVOC_2306_log_LODrev.Rdata"))
```

```{r}
#load(paste0(path_out, "/data/Sugi/BVOC/pca_BVOC_2306_log_LODrev.Rdata"))
col_BVOC <- c(rep("green3", 12), "purple3", rep("blue3", 2))
col_pop <- colorRampPalette(c("dodgerblue", "orangered"))(3)

p_pca <- autoplot(pca_BVOC_log_rm_LODrev, 
                  data = full_join(rownames_to_column(BVOC_2306_log_rm, var = "sampleID"),
                                   data.frame(rowData(BVOC_2306_log)) %>% dplyr::select(sampleID, Population),
                          by = "sampleID"), 
                  x = 1, y = 2,
                  color = "Population", 
                  scale = 1,
                  loadings = TRUE,
                  loadings.size = 5.5,
                  loadings.colour = col_BVOC,
                  loadings.label = TRUE,
                  loadings.label.size = 5.5 * .352777778,
                  loadings.label.colour = "black"
                  ) +

#scale loading vectors
#see https://rdrr.io/cran/ggfortify/src/R/plotlib.R
#loadings_sc <- data.frame(PC1 = pca_BVOC_log_rm_LODrev$rotation[, 1], 
#                          PC2 = pca_BVOC_log_rm_LODrev$rotation[, 2], 
#                          label = rownames(pca_BVOC_log_rm_LODrev$rotation))
#scaler <- min(max(abs(p_pca$data$PC1)) / max(abs(loadings_sc$PC1)),
#              max(abs(p_pca$data$PC1)) / max(abs(loadings_sc$PC2)))
#
#loadings_sc[, 1:2] <- loadings_sc[, 1:2] * scaler * 0.8
#loadings_sc$label <- gg_italic(loadings_sc$label, "-")
#
#p_pca <- p_pca + geom_segment(data = loadings_sc, 
#                              mapping = aes(x = 0, xend = PC1, y = 0, yend = PC2), 
#                              arrow = arrow(length = unit(2.0, "mm")), 
#                              color = col_BVOC, 
#                              linewidth = 0.5) +
#  geom_text(data = loadings_sc, 
#            mapping = aes(x = PC1, y = PC2, label = label),
#            size = 5.5 * .352777778,
#            color = "black",
#            parse = TRUE) +
  coord_fixed(ratio = 1) +
  theme_classic(base_size = 11) +
  labs(color = "Population") +
  scale_color_manual(values = col_pop, labels = c("Ajigazawa", "Azouji", "Yakushima")) +
  mytheme + theme(legend.position = "none")

show(p_pca)

ggsave(plot = p_pca, filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/figures/pca_BVOC_log_LODrev.png"), 
       dpi = 300, width = 160, height = 160, units = "mm")
```

```{r}
#PC2 and PC3
p_pca23 <- autoplot(pca_BVOC_log_rm_LODrev,
                    data = full_join(rownames_to_column(BVOC_2306_log_rm, var = "sampleID"),
                                     data.frame(rowData(BVOC_2306_log)) %>% dplyr::select(sampleID, Population),
                                     by = "sampleID"),
                    x = 2, y = 3,
                    color = "Population",
                    scale = 1,
                    loadings = TRUE,
                    loadings.colour = col_BVOC,
                    loadings.size = 5.5,
                    loadings.label = TRUE,
                    loadings.label.size = 10 * .352777778,
                    loadings.label.colour = "black"
                    ) +
  coord_fixed(ratio = 1) +
  theme_classic(base_size = 12) +
  labs(color = "Population") +
  scale_color_manual(values = col_pop, labels = c("Ajigazawa", "Azouji", "Yakushima")) +
  mytheme + theme(legend.position = "none")

show(p_pca23)

ggsave(plot = p_pca23,
       filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/figures/pca_BVOC_log_LODrev23.png"), 
       dpi = 300, width = 160, height = 160, units = "mm")

#Don't do the command below after editing with Inkscape
ggsave(plot = p_pca23,
       filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/figures/pca_BVOC_log_LODrev23.pdf"), 
       dpi = 300, width = 160, height = 160, units = "mm", scale = 1, family = "Helvetica")
```

#merge plot

```{r}
p_pca_none <- p_pca + theme(legend.position = "bottom", 
                            legend.title = element_text(size = 7), 
                            legend.text = element_text(size = 7))
legend <- gtable_filter(ggplotGrob(p_pca_none), "guide-box")
p_pca_none <- p_pca + theme(legend.position = "none")

pl_BVOC <- arrangeGrob(p_BVOC, top = create_label("A"))
pl_pca <- arrangeGrob(p_pca_none, top = create_label("B"))

layout <- rbind(c(1, 2), c(1, 3))

p_merge <- grid.arrange(pl_BVOC, pl_pca, legend, 
                        layout_matrix = layout, 
                        widths = c(5.5, 4.5), 
                        heights = c(9, 1)
                        )

ggsave(plot = p_merge,
       filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/figures/barplot_BVOC_pca_LODrev.png"),
       dpi = 300, width = 160, height = 80, units = "mm", scale = 1)

#Don't do below command after editing with Inkscape
ggsave(plot = p_merge,
       filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/figures/barplot_BVOC_pca1_LODrev.pdf"), 
       dpi = 300, width = 160, height = 80, units = "mm", scale = 1, family = "Helvetica")
```

#LM (to test the correlations between latitude and BVOCs emission rates)

```{r}
#to test the differences of PC1, 2 among groups, perform ANOVA test
#merge metadata and the result of PCA
data_pca <- rownames_to_column(data.frame(pca_BVOC_log_rm_LODrev$x), var = "sampleID")
data_pca <- full_join(data.frame(rowData(BVOC_2306_log)) %>% dplyr::select(sampleID,
                                                                           Population,
                                                                           latitude,
                                                                           longitude,
                                                                           altitude,
                                                                           PC1_clim,
                                                                           PC2_clim),
                      data_pca,
                      by = "sampleID")

#merge log-transformed total basal emission rate
df_total <- data.frame(total = log(rowSums(assay(BVOC_2306)), base = 10))
df_total <- rownames_to_column(df_total, var = "sampleID")
data_pca <- full_join(data_pca, df_total, by = "sampleID")

data_pca <- full_join(data_pca,
                      BVOC_2306_log_rm %>% rownames_to_column(var = "sampleID"),
                      by = "sampleID")
```

```{r}
#full model (use PC1 and PC2 for climatic data)
model_pc1_clim <- lm(PC1 ~ PC1_clim + PC2_clim, data = data_pca)
model_pc2_clim <- lm(PC2 ~ PC1_clim + PC2_clim, data = data_pca)
model_pc3_clim <- lm(PC3 ~ PC1_clim + PC2_clim, data = data_pca)
model_total_clim <- lm(total ~ PC1_clim + PC2_clim, data = data_pca)

anova(model_pc1_clim)
anova(model_pc2_clim)
anova(model_pc3_clim)
anova(model_total_clim)
#terpene PC1 is significantly positively correlated with climatic PC1, while terpene PC3 is significantly negatively correlated with climatic PC1

write.csv(anova(model_pc1_clim), 
          file = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/analysis/BVOC_pc1_AOV_climtot_LODrev.csv"))
write.csv(anova(model_pc2_clim), 
          file = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/analysis/BVOC_pc2_AOV_climtot_LODrev.csv"))
write.csv(anova(model_pc3_clim),
          file = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/analysis/BVOC_pc3_AOV_climtot_LODrev.csv"))
write.csv(anova(model_total_clim), 
          file = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/analysis/BVOC_total_AOV_climtot_LODrev.csv"))
```

##model selection

```{r}
#Since the climatic PC1 is perfectly corresponded to the climatic PC2, we can use either of them as an explanatory variable
#perform model selection
sel_pc1_clim <- stepAIC(model_pc1_clim)
sel_pc2_clim <- stepAIC(model_pc2_clim)
sel_pc3_clim <- stepAIC(model_pc3_clim)
sel_total_clim <- stepAIC(model_total_clim)

summary(sel_pc1_clim)
summary(sel_pc2_clim)
summary(sel_pc3_clim)
summary(sel_total_clim)

write.csv(cbind(summary(sel_pc1_clim)$coefficients, 
                AIC = summary(sel_pc1_clim)$aic), 
          file = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/analysis/BVOC_pc1_sel_clim_LODrev.csv"))

write.csv(cbind(summary(sel_pc2_clim)$coefficients, 
                AIC = summary(sel_pc2_clim)$aic), 
          file = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/analysis/BVOC_pc2_sel_clim_LODrev.csv"))
write.csv(cbind(summary(sel_pc3_clim)$coefficients, 
                AIC = summary(sel_pc3_clim)$aic),
          file = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/analysis/BVOC_pc3_sel_clim_LODrev.csv"))
write.csv(cbind(summary(sel_total_clim)$coefficients, 
                AIC = summary(sel_total_clim)$aic), 
          file = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/analysis/BVOC_total_sel_clim_LODrev.csv"))
```

##plot LM with climatic PCs

```{r}
#climatic PC1
p_pc1pc1 <- ggplot(data = data_pca, mapping = aes(x = PC1_clim, y = PC1, color = Population)) +
  geom_smooth(method = "lm", color = "black", linewidth = .7, alpha = 0.1) +
  geom_point() +
  labs(x = "Climatic PC1", y = "Terpene PC1", color = "Population") +
  scale_color_manual(values = col_pop, labels = c("Ajigasawa", "Azouji", "Yakushima")) +
  theme_classic(base_size = 12) + mytheme +
  NULL

p_pc2pc1 <- ggplot(data = data_pca, mapping = aes(x = PC1_clim, y = PC2, color = Population)) +
  geom_point() +
  labs(x = "Climatic PC1", y = "Terpene PC2", color = "Population") +
  scale_color_manual(values = col_pop, labels = c("Ajigasawa", "Azouji", "Yakushima")) +
  theme_classic(base_size = 12) + mytheme +
  NULL

p_pc3pc1 <- ggplot(data = data_pca, mapping = aes(x = PC1_clim, y = PC3, color = Population)) +
  geom_smooth(method = "lm", color = "black", linewidth = .7, alpha = 0.1) +
  geom_point() +
  labs(x = "Climatic PC1", y = "Terpene PC3", color = "Population") +
  scale_color_manual(values = col_pop, labels = c("Ajigasawa", "Azouji", "Yakushima")) +
  theme_classic(base_size = 12) + mytheme +
  NULL

#climatic PC2
p_pc1pc2 <- ggplot(data = data_pca, mapping = aes(x = PC2_clim, y = PC1, color = Population)) +
  geom_point() +
  labs(x = "Climatic PC2", y = "Terpene PC1", color = "Population") +
  scale_color_manual(values = col_pop, labels = c("Ajigasawa", "Azouji", "Yakushima")) +
  theme_classic(base_size = 12) + mytheme +
  NULL

p_pc2pc2 <- ggplot(data = data_pca, mapping = aes(x = PC2_clim, y = PC2, color = Population)) +
  geom_point() +
  labs(x = "Climatic PC2", y = "Terpene PC2", color = "Population") +
  scale_color_manual(values = col_pop, labels = c("Ajigasawa", "Azouji", "Yakushima")) +
  theme_classic(base_size = 12) + mytheme +
  NULL

p_pc3pc2 <- ggplot(data = data_pca, mapping = aes(x = PC2_clim, y = PC3, color = Population)) +
  geom_point() +
  labs(x = "Climatic PC2", y = "Terpene PC3", color = "Population") +
  scale_color_manual(values = col_pop, labels = c("Ajigasawa", "Azouji", "Yakushima")) +
  theme_classic(base_size = 12) + mytheme +
  NULL

show(p_pc1pc1)
show(p_pc2pc1)
show(p_pc3pc1)
show(p_pc1pc2)
show(p_pc2pc2)
show(p_pc3pc2)
```

```{r}
##arrange plots
pl_pc2pc1 <- p_pc2pc1 + theme(legend.position = "bottom")
legend <- gtable_filter(ggplotGrob(pl_pc2pc1), "guide-box")
pl_pc1pc1 <- p_pc1pc1 + theme(legend.position = "none")
pl_pc2pc1 <- p_pc2pc1 + theme(legend.position = "none")
pl_pc3pc1 <- p_pc3pc1 + theme(legend.position = "none")
pl_pc1pc2 <- p_pc1pc2 + theme(legend.position = "none")
pl_pc2pc2 <- p_pc2pc2 + theme(legend.position = "none")
pl_pc3pc2 <- p_pc3pc2 + theme(legend.position = "none")

pl_pc1pc1 <- arrangeGrob(pl_pc1pc1, top = create_label("A"))
pl_pc1pc2 <- arrangeGrob(pl_pc1pc2, top = create_label("B"))
pl_pc2pc1 <- arrangeGrob(pl_pc2pc1, top = create_label("C"))
pl_pc2pc2 <- arrangeGrob(pl_pc2pc2, top = create_label("D"))
pl_pc3pc1 <- arrangeGrob(pl_pc3pc1, top = create_label("E"))
pl_pc3pc2 <- arrangeGrob(pl_pc3pc2, top = create_label("F"))

layout <- rbind(c(1, 2), c(3, 4), c(5, 6), c(7, 7))

p_lm <- grid.arrange(pl_pc1pc1, pl_pc1pc2, pl_pc2pc1, pl_pc2pc2, pl_pc3pc1, pl_pc3pc2, legend,
                     layout_matrix = layout, widths = c(1, 1), heights = c(9, 9, 9, 3))

ggsave(plot = p_lm,
       filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/figures/LM_terpene_climate1_LODrev.pdf"), 
       dpi = 300, width = 160, height = 160, units = "mm", scale = 1)
```
