---
title: "pca_BVOC"
output: html_document
date: "2024-10-10"
---

#load packages

```{r}
library(readxl)
library(phyloseq)
library(tidyverse)
library(vegan)
library(glm2)
library(car)
library(MASS)
library(ggfortify)
library(RColorBrewer)
library(scales)
library(gridExtra)
library(grid)
library(gtable)
```

#path to raw-data directory (change "path" to your raw-data directory)

```{r}
#create "path" file, and define "path" as your raw-data directory(character vector) in the file
#"path" is raw-data directory, and "path_out" is output file directory

source("../scripts/path.R")
```

#source codes

```{r}
source("../R/label.R")
```

#read processed data

```{r import}
metadata <- read.csv(paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/processed_data/BVOC/metadata_16S_BVOC.csv"), row.names = 1)
rownames(metadata) <- formatC(as.numeric(rownames(metadata)), width = 4, flag = "0")

metadata$cloneID <- as.factor(metadata$cloneID)
metadata$population <- as.factor(metadata$population)
metadata$site <- as.factor(metadata$site)
metadata$date <- as.factor(metadata$date)

#population metadata
meta_pop <- read_excel(paste0(path_out, "/data/Sugi/metadata_2306.xlsx"), sheet = "location")

#result of PCA on climatic variables
load(paste0(path_out, "/data/Sugi/pca_climate.Rdata"))
df_pcaclim <- data.frame(pca_clim$x)
colnames(df_pcaclim) <- paste0(colnames(df_pcaclim), "_clim")

#merge population metadata and PCA result
meta_pop <- cbind(meta_pop, df_pcaclim)

#basal emission rates of BVOCs
BVOC_2306 <- read_excel(paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/processed_data/BVOC/BVOC_summary_240122.xlsx"), 
                       sheet = "2306_KAWATABI")
BVOC_2306 <- column_to_rownames(BVOC_2306, var = "samplename")

#log-transformed BVOC emission data
load(paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/processed_data/BVOC/BVOC_2306_16S_log.Rdata"))
```

#Barplot of basal emission rate

```{r}
#gather the emission data before plotting
BVOC_2306_ga <- rownames_to_column(BVOC_2306, var = "ID")
BVOC_2306_ga <- cbind(population = metadata$population, BVOC_2306_ga)
BVOC_2306_ga <- gather(BVOC_2306_ga, "BVOC", "emission", c(-ID, -population))

#assign colors to each terpene
col_BVOC <- c(colorRampPalette(c("green2", "grey30", "yellow2"))(12), 
              "purple3", "blue3")

#draw barplot
p_BVOC <- ggplot(data = BVOC_2306_ga, mapping = aes(x = ID, y = emission, 
                                                    fill = factor(BVOC, 
                                                                  levels = colnames(BVOC_2306))))
p_BVOC <- p_BVOC + geom_bar(stat = "identity")
p_BVOC <- p_BVOC + theme_classic()
p_BVOC <- p_BVOC + scale_fill_manual(values = col_BVOC)
p_BVOC <- p_BVOC + scale_y_continuous(labels = label_comma())
p_BVOC <- p_BVOC + facet_wrap(~ population, scales = "free_x")
p_BVOC <- p_BVOC + labs(fill = "Terpenes")
p_BVOC <- p_BVOC + 
  ylab(expression(paste("Basal Emission Rate (ng ", {gdw^-1}, " ", {h^-1}, ")")))
p_BVOC <- p_BVOC + theme(axis.title.x = element_blank(), 
                         axis.text.x = element_blank(), 
                         axis.ticks.x = element_blank(), 
                         
                         legend.key.size = unit(3, "mm"), 
                         legend.text = element_text(size = 10.5))
show(p_BVOC)

ggsave(plot = p_BVOC, filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/figures/barplot_BVOC.png"), 
       dpi = 400, width = 150, height = 80, units = "mm")
```

#pca

```{r}
#remove kaurene from dataframe
#sapply(c("kaurene"), grep, colnames(BVOC_log_ps))
pca_BVOC_log_rm <- prcomp(BVOC_2306_log[, -c(14)], 
                          scale. = TRUE)
summary(pca_BVOC_log_rm)

#save(pca_BVOC_log_rm, file = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/processed_data/BVOC/pca_BVOC_2306_16S_log.Rdata"))
```

```{r}
col_BVOC <- c(rep("green4", 12), "purple3", "blue3")
col_pop <- colorRampPalette(c("blue3", "orange2"))(3)

p_pca <- autoplot(pca_BVOC_log_rm, 
                  data = cbind(BVOC_2306_log[, -c(14)], 
                               population = metadata$population), 
                  x = 1, y = 2,
                  color = "population", 
                  size = 2.5, 
                  loadings = TRUE, 
                  loadings.color = "grey", 
                  loadings.label = TRUE, 
                  loadings.label.color = col_BVOC[-c(14)], 
                  loadings.label.size = 4) + 
  coord_fixed(ratio = 1) + 
  theme_classic() + 
  labs(color = "Population") + 
  scale_color_manual(values = col_pop, labels = c("Ajigazawa", "Azouji", "Yakushima")) + 
  theme(legend.title = element_text(size = 13), 
        legend.text = element_text(size = 10))

show(p_pca)

ggsave(plot = p_pca, filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/figures/pca_BVOC_log.png"), 
       dpi = 400, width = 150, height = 150, units = "mm")
```

#merge plot

```{r}
p_pca_none <- p_pca + theme(legend.position = "inside")
legend <- gtable_filter(ggplotGrob(p_pca_none), "guide-box")
p_pca_none <- p_pca_none + theme(legend.position = "none")

pl_BVOC <- arrangeGrob(p_BVOC, top = create_label("a"))
pl_pca <- arrangeGrob(p_pca_none, top = create_label("b"))

layout <- rbind(c(1, 2), c(1, 3))

p_merge <- grid.arrange(pl_BVOC, pl_pca, legend, 
                        layout_matrix = layout, 
                        widths = c(3, 2), 
                        heights = c(2, 1)
                        )

ggsave(plot = p_merge, filename = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/figures/barplot_BVOC_pca.png"), 
       dpi = 400, width = 150, height = 80, units = "mm", scale = 2)
```

#GLM (to test the correlations between latitude and BVOCs emission rates)

```{r}
#to test the differences of PC1, 2 among groups, perform ANOVA test
#merge metadata and the result of PCA
data_pca <- rownames_to_column(data.frame(pca_BVOC_log_rm$x))
data_pca <- merge(metadata, data_pca, by.x = "samplename", by.y = "rowname")

#merge log-transformed total basal emission rate
df_total <- data.frame(total = BVOC_2306_total_log)
df_total <- rownames_to_column(df_total)
data_pca <- merge(data_pca, df_total, by.x = "samplename", by.y = "rowname")

#merge BVOCs emission profile
df_BVOC <- rownames_to_column(BVOC_2306_log)
data_pca <- merge(data_pca, df_BVOC, by.x = "samplename", by.y = "rowname")

#merge population metadata
data_pca <- merge(data_pca, meta_pop, by.x = "population", by.y = "population", all.x = TRUE)
```

```{r}
#full model (use PC1 and PC2 for climatic data)
model_pc1_clim <- glm2(PC1 ~ PC1_clim + PC2_clim, data = data_pca, 
                       family = gaussian(link = "identity"))
model_pc2_clim <- glm2(PC2 ~ PC1_clim + PC2_clim, data = data_pca, 
                       family = gaussian(link = "identity"))
model_total_clim <- glm2(total ~ PC1_clim + PC2_clim, data = data_pca, 
                         family = gaussian(link = "identity"))

summary(model_pc1_clim)
summary(model_pc2_clim)
summary(model_total_clim)
#none of the models are significant when both PC1 & PC2 included
```

##test multicollinearity

```{r}
vif(model_pc1_clim)
#multicollinearity is not detected

#perform model selection and compare results with one covariate models
set.seed(123)
selc_PC1_clim <- stepAIC(model_pc1_clim)
selc_PC2_clim <- stepAIC(model_pc2_clim)
selc_total_clim <- stepAIC(model_total_clim)
#PC1 for climatic data was selected only for the terpene PC1 model
```

```{r}
#output models with climatic PC1 as an explanatory variable
model_pc1_clim <- glm2(PC1 ~ PC1_clim, data = data_pca, 
                       family = gaussian(link = "identity"))
model_pc2_clim <- glm2(PC2 ~ PC1_clim, data = data_pca, 
                       family = gaussian(link = "identity"))
model_total_clim <- glm2(total ~ PC1_clim, data = data_pca, 
                         family = gaussian(link = "identity"))

write.csv(cbind(summary(model_pc1_clim)$coefficients, 
                AIC = summary(model_pc1_clim)$aic), 
          file = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/analysis/BVOC_pc1_glm_clim.csv"))

write.csv(cbind(summary(model_pc2_clim)$coefficients, 
                AIC = summary(model_pc2_clim)$aic), 
          file = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/analysis/BVOC_pc2_glm_clim.csv"))

write.csv(cbind(summary(model_total_clim)$coefficients, 
                AIC = summary(model_total_clim)$aic), 
          file = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/analysis/BVOC_total_glm_clim.csv"))
```

```{r}
model_pc1 <- glm(PC1 ~ latitude, data = data_pca)
model_pc2 <- glm(PC2 ~ latitude, data = data_pca)
model_total <- glm(total ~ latitude, data = data_pca)

summary(model_pc1)
summary(model_pc2)
summary(model_total)

write.csv(cbind(summary(model_pc1)$coefficients, 
                AIC = summary(model_pc1)$aic), 
          file = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/analysis/BVOC_pc1_glm.csv"))

write.csv(cbind(summary(model_pc2)$coefficients, 
                AIC = summary(model_pc2)$aic), 
          file = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/analysis/BVOC_pc2_glm.csv"))

write.csv(cbind(summary(model_total)$coefficients, 
                AIC = summary(model_total)$aic), 
          file = paste0(path_out, "/231202_Sugi_phyllosphere_June_16S/analysis/BVOC_total_glm.csv"))
```

